# Generated by Django 5.2 on 2025-11-17 13:32

from django.db import connection, migrations


def check_and_add_field(apps, schema_editor):
    """Check if column and index exist before adding them."""
    with connection.cursor() as cursor:
        # Check if column exists in SQLite
        cursor.execute(
            """
            SELECT COUNT(*) FROM pragma_table_info('api_order') 
            WHERE name='delivery_date_order_id'
        """
        )
        column_exists = cursor.fetchone()[0] > 0

        # Check if index exists
        cursor.execute(
            """
            SELECT COUNT(*) FROM sqlite_master 
            WHERE type='index' AND name='order_delivery_date_id_idx'
        """
        )
        index_exists = cursor.fetchone()[0] > 0

        # Add column if it doesn't exist
        if not column_exists:
            cursor.execute(
                """
                ALTER TABLE api_order 
                ADD COLUMN delivery_date_order_id INTEGER NULL
            """
            )

        # Add index if it doesn't exist
        if not index_exists:
            cursor.execute(
                """
                CREATE INDEX order_delivery_date_id_idx 
                ON api_order(delivery_date, delivery_date_order_id)
            """
            )


def reverse_migration(apps, schema_editor):
    """Reverse migration - remove index if it exists."""
    with connection.cursor() as cursor:
        # Remove index if exists (SQLite doesn't support DROP COLUMN easily)
        cursor.execute("DROP INDEX IF EXISTS order_delivery_date_id_idx")


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(check_and_add_field, reverse_migration),
    ]
