# Generated by Django 5.2 on 2025-11-17 13:32

class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_date_order_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Auto-incrementing order ID per delivery date (starts at 1 for each date)",
                null=True,
                verbose_name="Order ID",
            ),
        )
    ]
