# Generated by Django 5.2 on 2025-05-03 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-delivery_date"],
                "permissions": [
                    ("can_change_note_and_status", "Can change order status and notes")
                ],
                "verbose_name_plural": "Orders",
            },
        ),
    ]
