# Generated by Django 5.2 on 2025-11-30 02:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_add_holiday_fee_rename_price_to_base_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="holiday_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Holiday fee percentage (0-100)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["delivery_date", "delivery_date_order_id"],
                name="order_delivery_date_id_idx",
            ),
        ),
    ]
