# Generated by Django 5.2 on 2025-11-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date_order_id',
            field=models.PositiveIntegerField(blank=True, help_text='Auto-incrementing order ID per delivery date (starts at 1 for each date)', null=True, verbose_name='Order ID'),
        ),
    ]
