
# Generated by Django 5.2 on 2025-11-24 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_order_delivery_date_order_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productimage',
            name='api_product_product_af3f05_idx',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='is_primary',
        ),
    ]
