# Generated by Django 5.2 on 2025-12-02 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order_holiday_fee'),
        ('api', '0005_remove_is_primary_field'),
    ]

    operations = [
    ]
