# Generated by Django 5.2 on 2025-05-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_order_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
