# Generated by Django 5.2 on 2025-05-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_order_delivery_fee_order_order_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_home_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
