# Generated by Django 5.2 on 2025-05-25 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_order_is_home_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoice_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
