# Generated by Django 5.2 on 2025-05-25 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_order_invoice_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default='2025-05-23'),
            preserve_default=False,
        ),
    ]
