# Generated by Django 5.2 on 2025-05-25 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_order_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_home_delivery',
            field=models.BooleanField(default=True),
        ),
    ]
