# Generated by Django 5.2 on 2025-05-25 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_order_is_home_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_home_delivery',
            field=models.BooleanField(default=True, verbose_name='Home Delivery'),
        ),
    ]
