# Generated by Django 5.2 on 2025-05-25 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_productcategory_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='parent',
        ),
    ]
