# Generated by Django 5.2 on 2025-06-02 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_productcategory_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='categories',
        ),
    ]
