# Generated by Django 5.2 on 2025-07-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_category_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee_manual',
            field=models.BooleanField(default=False, help_text='Check to set the delivery fee manually. Uncheck to auto-calculate.'),
        ),
    ]
