# Generated by Django 5.2 on 2025-07-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_alter_product_options_alter_product_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_fee_manual",
            field=models.BooleanField(
                default=False,
                help_text="Check to set the delivery fee manually. Uncheck to auto-calculate.",
            ),
        ),
    ]
