# Generated by Django 5.2 on 2025-10-12 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_delete_stock"),
    ]

    operations = [
        # No operation needed - Stock model was never created in the database
    ]
