# Generated by Django 5.2 on 2025-10-29 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_order_payment_intent_id_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='cart',
            name='delivery_fee_manual',
            field=models.BooleanField(default=False, help_text='Check to set the delivery fee manually'),
        ),
        migrations.AddField(
            model_name='cart',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='cart',
            name='is_home_delivery',
            field=models.BooleanField(default=True, verbose_name='Home Delivery'),
        ),
        migrations.AddField(
            model_name='cart',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
