# Generated by Django 5.2 on 2025-10-29 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_add_cart_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='delivery_fee_manual',
        ),
    ]
