# Generated by Django 5.2 on 2025-11-22 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_add_email_sent_at_to_emailverificationtoken'),
        ('api', '0027_remove_cart_delivery_fee_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='account.address'),
        ),
    ]
