# Generated by Django 5.2 on 2025-12-09 03:34

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_productimage_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sendcloud_parcel_id',
            field=models.IntegerField(blank=True, help_text='Sendcloud parcel ID for tracking', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_carrier',
            field=models.CharField(blank=True, help_text='Shipping carrier name (e.g., DPD, Royal Mail)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost of shipping charged to customer', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_label_url',
            field=models.URLField(blank=True, help_text='Shipping label URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method_id',
            field=models.IntegerField(blank=True, help_text='Sendcloud shipping method ID', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_service_name',
            field=models.CharField(blank=True, help_text='Shipping service name (e.g., Standard, Express)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_tracking_number',
            field=models.CharField(blank=True, help_text='Shipment tracking number', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_tracking_url',
            field=models.URLField(blank=True, help_text='Shipment tracking URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
