# Generated by Django 5.2 on 2025-12-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_order_sendcloud_parcel_id_order_shipping_carrier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_error_message',
            field=models.TextField(blank=True, help_text='Error message if shipment creation failed', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(blank=True, choices=[('pending_shipment', 'Pending Shipment'), ('label_created', 'Label Created'), ('shipment_failed', 'Shipment Failed'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered')], help_text='Current shipping status', max_length=50, null=True),
        ),
    ]
