# Generated by Django 5.2 on 2025-12-10 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_order_shipping_error_message_order_shipping_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='sendcloud_parcel_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_carrier',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_cost',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_error_message',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_label_url',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_method_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_service_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_tracking_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_tracking_url',
        ),
    ]
