# Generated by Django 5.2 on 2026-01-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_orderitem_item_name_orderitem_item_price_product_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vat',
            field=models.BooleanField(default=False, help_text='Check to apply 20% VAT, uncheck for 0% VAT'),
        ),
    ]
