# Generated by Django 5.2 on 2026-02-04 14:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_product_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Weight of the product', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
