# Generated by Django 5.2 on 2026-02-11 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_order_status_productreview'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productreview',
            name='unique_product_user_review',
        ),
    ]
