# Generated by Django 5.2 on 2026-03-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_product_api_product_name_73c704_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('ready_to_ship', 'Ready to ship'), ('issued', 'Issued'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
    ]
