# Generated by Django 5.2 on 2026-03-31 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0042_ready_to_ship_and_packaging"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Parcel weight (kg) for Sendcloud: sum(product.weight×qty), min 0.1. Updated when the order or its lines are saved.",
                max_digits=10,
                null=True,
            ),
        ),
    ]
