# Generated by Django 5.2 on 2026-05-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold_orders_count',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Distinct completed orders containing this product.'),
        ),
        migrations.AddField(
            model_name='product',
            name='sold_quantity',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Total units sold (sum of order line quantities in paid/ready/issued orders).'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-sold_quantity', 'id'], name='api_product_sold_qu_5e85a3_idx'),
        ),
    ]
