# Generated by Django 5.2 on 2026-05-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_product_sales_counters'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(db_index=True, default=True, help_text='If disabled, the product is hidden from the storefront and API listings.'),
        ),
    ]
