# Generated by Django 5.2 on 2026-05-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_product_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='sold_quantity',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Total units sold across products in this category (sum of order line quantities in paid/ready/issued orders).'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('issued', 'Issued'), ('ready_to_ship', 'Ready to ship'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
    ]
