# Generated by Django 5.2 on 2026-05-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_productcategory_sold_quantity_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='category_groups', to='api.productcategory', verbose_name='Child categories')),
            ],
            options={
                'verbose_name': 'Category group',
                'verbose_name_plural': 'Category groups',
                'ordering': ['name'],
            },
        ),
    ]
