# Generated by Django 5.2 on 2026-05-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_categorygroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('admin', 'Admin'), ('system', 'System')], db_index=True, default='admin', help_text='Where this order was created (frontend website, admin panel, or system).', max_length=30),
        ),
    ]
