# Generated by Django 5.2 on 2026-06-29 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_sync_legacy_review_columns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='admin_replied_at',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='admin_reply',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='delivery_rating',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='food_quality_rating',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='is_verified_order',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='order',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='packaging_rating',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='service_rating',
        ),
    ]
