# Generated by Django 5.2 on 2026-07-02 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_remove_legacy_review_columns'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Product Categories'},
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='parent',
        ),
    ]
