# Generated by Django 5.2 on 2026-07-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorygroup',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional group image (single). Upload or replace via admin.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional category image (single). Upload or replace via admin.', max_length=500, null=True),
        ),
    ]
