# Generated by Django 5.2 on 2026-07-17 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_billing_address'),
        ('api', '0054_category_and_group_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bill_use_delivery_address',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='account.billingaddress'),
        ),
    ]
