# Generated by Django 5.2 on 2026-08-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_billing_address'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['active', '-created_at'], name='api_product_active_650229_idx'),
        ),
    ]
