# Generated by Django 5.2 on 2026-09-17 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_reviewimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promo_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Automatic promotion discount (e.g. Jerky 5+1) frozen at checkout. Applied on top of any coupon discount.', max_digits=7, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='free_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Units on this line given away by an automatic promotion. Included in quantity (not added to it); their value is deducted via promo_discount.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='product',
            name='promo_group',
            field=models.CharField(blank=True, choices=[('jerky_5_1', 'Jerky 5+1 (buy 5 get 1 free)')], db_index=True, default='', help_text='Automatic multi-buy promotion this product belongs to. Leave empty for no promotion. Units pool across every product sharing the same group.', max_length=32),
        ),
    ]
