# Generated by Django 5.2 on 2026-10-02 00:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_order_promo_discount_orderitem_free_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='promo_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Automatic promotion discount (e.g. Jerky 5+1), recalculated when the order is saved. Applied on top of any coupon discount.', max_digits=7, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='promo_group',
            field=models.CharField(blank=True, choices=[('jerky_5_1', 'Jerky 5+1 (buy 5 get 1 free)')], db_index=True, default='', help_text='Deprecated — unused for eligibility. Jerky 5+1 is driven by membership in the Jerky ProductCategory (see JERKY_PROMO_CATEGORY_ID / JERKY_PROMO_CATEGORY_NAME). Field retained to avoid a migration; safe to leave empty.', max_length=32),
        ),
    ]
