# Generated by Django 5.2 on 2026-05-30 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0049_order_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('telegram', 'Telegram')], max_length=30)),
                ('event', models.CharField(choices=[('new_frontend_order', 'New frontend order')], max_length=100)),
                ('recipient', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=30)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='api.order')),
            ],
            options={
                'indexes': [models.Index(fields=['channel', 'event', 'status'], name='notificatio_channel_a3febd_idx')],
                'constraints': [models.UniqueConstraint(fields=('order', 'channel', 'event'), name='notifications_unique_order_channel_event')],
            },
        ),
    ]
