# Generated by Django 5.2 on 2026-01-21 07:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0036_orderitem_item_name_orderitem_item_price_product_vat'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Invoice Number Sequence',
                'verbose_name_plural': 'Invoice Number Sequences',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.PositiveBigIntegerField(help_text='Sequential invoice number allocated at issuance.', unique=True)),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('PART_PAID', 'Part paid'), ('PAID', 'Paid'), ('VOID', 'Void')], default='ISSUED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_snapshot', models.JSONField(default=dict)),
                ('billing_address_snapshot', models.JSONField(default=dict)),
                ('seller_snapshot', models.JSONField(default=dict)),
                ('delivery_date', models.DateField(default=django.utils.timezone.localdate)),
                ('delivery_date_order_id', models.PositiveIntegerField(default=0)),
                ('holiday_fee_percent', models.DecimalField(decimal_places=2, default=0, help_text='Percent (0-100)', max_digits=5)),
                ('holiday_fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('invoice_link', models.CharField(blank=True, default='', help_text='S3 key/path to the rendered invoice PDF (immutable once set).', max_length=255)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True, default='')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='api.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_gross', models.DecimalField(decimal_places=2, default=0, help_text='Unit price including VAT (gross).', max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, help_text='Unit price excluding VAT (net).', max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vat_rate', models.DecimalField(decimal_places=4, default=0, help_text='VAT rate as a decimal (e.g. 0.20).', max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='billing.invoice')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='billing_inv_invoice_70511c_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'created_at'], name='billing_inv_status_bfbaa4_idx'),
        ),
    ]
