# Generated by Django 5.2 on 2026-01-25 16:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNoteNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Credit Note Number Sequence',
                'verbose_name_plural': 'Credit Note Number Sequences',
            },
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_note_number', models.PositiveBigIntegerField(help_text='Sequential credit note number allocated at issuance.', unique=True)),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('APPLIED', 'Applied')], default='ISSUED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, default='', help_text='Reason for issuing this credit note.')),
                ('customer_snapshot', models.JSONField(default=dict)),
                ('billing_address_snapshot', models.JSONField(default=dict)),
                ('seller_snapshot', models.JSONField(default=dict)),
                ('delivery_date', models.DateField(default=django.utils.timezone.localdate)),
                ('delivery_date_order_id', models.PositiveIntegerField(default=0)),
                ('holiday_fee_percent', models.DecimalField(decimal_places=2, default=0, help_text='Percent (0-100)', max_digits=5)),
                ('holiday_fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('credit_note_link', models.CharField(blank=True, default='', help_text='S3 key/path to the rendered credit note PDF (immutable once set).', max_length=255)),
                ('invoice', models.OneToOneField(help_text='The invoice this credit note cancels.', on_delete=django.db.models.deletion.PROTECT, related_name='credit_note', to='billing.invoice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditNoteLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_gross', models.DecimalField(decimal_places=2, default=0, help_text='Unit price including VAT (gross).', max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, help_text='Unit price excluding VAT (net).', max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vat_rate', models.DecimalField(decimal_places=4, default=0, help_text='VAT rate as a decimal (e.g. 0.20).', max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='billing.creditnote')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='creditnote',
            index=models.Index(fields=['credit_note_number'], name='billing_cre_credit__1a13d1_idx'),
        ),
        migrations.AddIndex(
            model_name='creditnote',
            index=models.Index(fields=['status', 'created_at'], name='billing_cre_status_37ed8d_idx'),
        ),
    ]
