# Generated by Django 5.2 on 2026-01-25 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_product_vat'),
        ('billing', '0002_creditnotenumbersequence_creditnote_and_more'),
    ]

    operations = [
        # Django's AlterField should automatically remove the unique constraint
        # when changing from OneToOneField to ForeignKey
        migrations.AlterField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='invoices',
                to='api.order',
            ),
        ),
    ]
