# Generated by Django 5.2 on 2026-01-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_invoice_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('INVOICE', 'Invoice'), ('CREDIT_NOTE', 'Credit Note')], help_text='Type of document this sequence is for.', max_length=20, unique=True)),
                ('last_number', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Document Number Sequence',
                'verbose_name_plural': 'Document Number Sequences',
                'ordering': ['document_type'],
            },
        ),
        migrations.DeleteModel(
            name='CreditNoteNumberSequence',
        ),
        migrations.DeleteModel(
            name='InvoiceNumberSequence',
        ),
    ]
