# Generated by Django 5.2 on 2026-09-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_documentnumbersequence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='promo_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='promo_label',
            field=models.CharField(blank=True, default='', help_text='Name of the promotion applied on the credited invoice.', max_length=100),
        ),
        migrations.AddField(
            model_name='creditnotelineitem',
            name='free_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Units on this line given away by a promotion (included in quantity).', max_digits=10),
        ),
        migrations.AddField(
            model_name='creditnotelineitem',
            name='promo_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Value of the free units on this line.', max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='promo_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='promo_label',
            field=models.CharField(blank=True, default='', help_text="Name of the applied promotion at issuance (e.g. 'Jerky 5+1').", max_length=100),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='free_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Units on this line given away by a promotion (included in quantity).', max_digits=10),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='promo_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Value of the free units on this line.', max_digits=10),
        ),
    ]
