# Generated by Django 5.2 on 2026-09-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_order_promo_discount_orderitem_free_quantity_and_more'),
        ('billing', '0005_creditnote_promo_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_public_token',
            field=models.CharField(blank=True, db_index=True, help_text='Cryptographically secure public token for /pay/invoice/<token>.', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_version',
            field=models.PositiveIntegerField(default=1, help_text='Bumped when the payable amount changes so Stripe sessions stay in sync.'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='stripe_payment_status',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['payment_public_token'], name='billing_inv_payment_3b9538_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['stripe_checkout_session_id'], name='billing_inv_stripe__1e01f0_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['stripe_payment_intent_id'], name='billing_inv_stripe__b6d2d4_idx'),
        ),
    ]
