# Generated by Django 5.2 on 2026-07-15 18:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FestivalNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('TICKET', 'Ticket'), ('FE_INVOICE', 'Festival Invoice'), ('FE_CREDIT_NOTE', 'Festival Credit Note')], max_length=20, unique=True)),
                ('last_number', models.PositiveBigIntegerField(default=0)),
                ('cycle_number', models.PositiveBigIntegerField(default=0, help_text='Incremented when the rotating ticket sequence wraps past 99.')),
            ],
            options={
                'verbose_name': 'Festival number sequence',
                'verbose_name_plural': 'Festival number sequences',
                'ordering': ['document_type'],
            },
        ),
        migrations.CreateModel(
            name='FestivalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveSmallIntegerField(help_text='Rotating display ticket number 1–99.')),
                ('cycle_number', models.PositiveBigIntegerField(default=0, help_text='Ticket sequence cycle at allocation time.')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField()),
                ('client_request_id', models.UUIDField(unique=True)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='PAID', max_length=20)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='festival_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FestivalInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('CREDITED', 'Credited')], default='PAID', max_length=20)),
                ('issued_at', models.DateTimeField()),
                ('subtotal_net', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_gross', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seller_snapshot', models.JSONField(default=dict)),
                ('vat_breakdown', models.JSONField(default=dict, help_text='VAT totals grouped by rate percentage.')),
                ('pdf_key', models.CharField(blank=True, default='', max_length=255)),
                ('credited_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='festival.festivalorder')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='FestivalPrinter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Festival printer', max_length=100)),
                ('mac_address', models.CharField(help_text='Ethernet MAC as 12 uppercase hex characters.', max_length=12, unique=True)),
                ('unique_id', models.CharField(blank=True, default='', max_length=64)),
                ('serial_number', models.CharField(blank=True, default='', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_status_code', models.CharField(blank=True, default='', max_length=64)),
                ('last_status_text', models.CharField(blank=True, default='', max_length=255)),
                ('printing_in_progress', models.BooleanField(default=False)),
                ('current_job_token', models.UUIDField(blank=True, null=True)),
                ('supported_media_types', models.JSONField(blank=True, default=list)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='festival_one_active_printer')],
            },
        ),
        migrations.CreateModel(
            name='FestivalPrintJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('batch_uuid', models.UUIDField(db_index=True)),
                ('job_type', models.CharField(choices=[('KITCHEN', 'Kitchen'), ('CUSTOMER', 'Customer'), ('KITCHEN_CANCELLATION', 'Kitchen cancellation'), ('CUSTOMER_CREDIT', 'Customer credit')], max_length=32)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('READY', 'Ready'), ('CLAIMED', 'Claimed'), ('PRINTED', 'Printed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='READY', max_length=20)),
                ('media_type', models.CharField(default='text/plain', max_length=64)),
                ('payload_text', models.TextField()),
                ('payload_checksum', models.CharField(max_length=64)),
                ('is_reprint', models.BooleanField(default=False)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_source', models.CharField(blank=True, choices=[('DELETE', 'DELETE acknowledgement'), ('INFERRED_FROM_POLL', 'Inferred from poll')], default='', max_length=32)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_result_code', models.CharField(blank=True, default='', max_length=64)),
                ('last_error', models.TextField(blank=True, default='')),
                ('audit_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='print_jobs', to='festival.festivalorder')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='print_jobs', to='festival.festivalprinter')),
                ('retry_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retries', to='festival.festivalprintjob')),
            ],
            options={
                'ordering': ['available_at', 'sequence', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='FestivalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('vat_rate', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='VAT percentage (0, 5, 20, …).', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('price', models.DecimalField(decimal_places=2, help_text='VAT-inclusive retail price.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'permissions': [('place_festival_order', 'Can place festival orders'), ('cancel_festival_order', 'Can cancel festival orders')],
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='festival_product_price_non_negative'), models.CheckConstraint(condition=models.Q(('vat_rate__gte', 0), ('vat_rate__lte', 100)), name='festival_product_vat_rate_range')],
            },
        ),
        migrations.CreateModel(
            name='FestivalOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('product_name', models.CharField(max_length=200)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='VAT-inclusive unit price snapshot.', max_digits=10)),
                ('vat_rate', models.DecimalField(decimal_places=0, help_text='VAT percentage snapshot.', max_digits=3)),
                ('line_net', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_vat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='festival.festivalorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='festival.festivalproduct')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FestivalCreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_note_number', models.CharField(max_length=32, unique=True)),
                ('issued_at', models.DateTimeField()),
                ('reason', models.TextField(blank=True, default='')),
                ('original_invoice_number', models.CharField(max_length=32)),
                ('subtotal_net', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_gross', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seller_snapshot', models.JSONField(default=dict)),
                ('vat_breakdown', models.JSONField(default=dict)),
                ('pdf_key', models.CharField(blank=True, default='', max_length=255)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='credit_note', to='festival.festivalinvoice')),
            ],
            options={
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['credit_note_number'], name='festival_fe_credit__f342a7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='festivalorder',
            index=models.Index(fields=['status', 'created_at'], name='festival_fe_status_77ddb1_idx'),
        ),
        migrations.AddIndex(
            model_name='festivalorder',
            index=models.Index(fields=['order_number', 'created_at'], name='festival_fe_order_n_c2ade2_idx'),
        ),
        migrations.AddConstraint(
            model_name='festivalorder',
            constraint=models.UniqueConstraint(fields=('order_number', 'id'), name='festival_order_number_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='festivalorder',
            constraint=models.CheckConstraint(condition=models.Q(('order_number__gte', 1), ('order_number__lte', 99)), name='festival_order_number_range'),
        ),
        migrations.AddConstraint(
            model_name='festivalorder',
            constraint=models.CheckConstraint(condition=models.Q(('total_price__gte', 0)), name='festival_order_total_non_negative'),
        ),
        migrations.AddIndex(
            model_name='festivalinvoice',
            index=models.Index(fields=['invoice_number'], name='festival_fe_invoice_949237_idx'),
        ),
        migrations.AddIndex(
            model_name='festivalinvoice',
            index=models.Index(fields=['status', 'issued_at'], name='festival_fe_status_675127_idx'),
        ),
        migrations.AddIndex(
            model_name='festivalprintjob',
            index=models.Index(fields=['printer', 'status', 'available_at'], name='festival_fe_printer_adfedf_idx'),
        ),
        migrations.AddIndex(
            model_name='festivalprintjob',
            index=models.Index(fields=['batch_uuid', 'sequence'], name='festival_fe_batch_u_c4bc35_idx'),
        ),
        migrations.AddIndex(
            model_name='festivalprintjob',
            index=models.Index(fields=['order'], name='festival_fe_order_i_d61a7a_idx'),
        ),
        migrations.AddIndex(
            model_name='festivalprintjob',
            index=models.Index(fields=['created_at'], name='festival_fe_created_1271a3_idx'),
        ),
        migrations.AddIndex(
            model_name='festivalprintjob',
            index=models.Index(fields=['status', 'created_at'], name='festival_fe_status_2ee2d2_idx'),
        ),
        migrations.AddConstraint(
            model_name='festivalprintjob',
            constraint=models.UniqueConstraint(fields=('batch_uuid', 'sequence'), name='festival_print_batch_sequence_unique'),
        ),
        migrations.AddConstraint(
            model_name='festivalprintjob',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gte', 1)), name='festival_print_sequence_positive'),
        ),
        migrations.AddConstraint(
            model_name='festivalorderitem',
            constraint=models.UniqueConstraint(fields=('order', 'product'), name='festival_order_item_unique_product'),
        ),
        migrations.AddConstraint(
            model_name='festivalorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='festival_order_item_quantity_positive'),
        ),
    ]
