# Generated by Django 5.2 on 2026-07-16 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0001_initial_festival'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festivalnumbersequence',
            name='cycle_number',
        ),
        migrations.RemoveField(
            model_name='festivalorder',
            name='cycle_number',
        ),
    ]
