# Generated by Django 5.2 on 2026-07-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0002_remove_festivalnumbersequence_cycle_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festivalnumbersequence',
            name='last_number',
            field=models.PositiveBigIntegerField(default=0, help_text='Ticket: last allocated display number (0–99, wraps to 1). Invoice/credit note: last allocated document number (no wrap).'),
        ),
        migrations.AddConstraint(
            model_name='festivalnumbersequence',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('document_type', 'TICKET'), _negated=True), ('last_number__lte', 99), _connector='OR'), name='festival_ticket_sequence_max_99'),
        ),
    ]
