# Generated by Django 5.2 on 2026-07-18 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0003_alter_festivalnumbersequence_last_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festivalorder',
            name='paid_at',
        ),
    ]
