# Generated by Django 5.2 on 2026-07-20 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0004_remove_festivalorder_paid_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='FestivalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Festival category',
                'verbose_name_plural': 'Festival categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='festivalproduct',
            options={'ordering': ['category__name', 'name'], 'permissions': [('place_festival_order', 'Can place festival orders'), ('cancel_festival_order', 'Can cancel festival orders')]},
        ),
        migrations.AddField(
            model_name='festivalproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='festival.festivalcategory'),
        ),
    ]
