# Generated by Django 5.2 on 2026-07-20 18:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0005_festival_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='FestivalAddition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, help_text='VAT-inclusive addition price.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
            options={
                'verbose_name': 'Addition',
                'verbose_name_plural': 'Additions',
                'ordering': ['addition_class__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FestivalAdditionClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Addition class',
                'verbose_name_plural': 'Addition classes',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='festivalorderitem',
            name='festival_order_item_unique_product',
        ),
        migrations.AddField(
            model_name='festivalorderitem',
            name='addition_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='festivalorderitem',
            name='addition_unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='VAT-inclusive addition unit price snapshot.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='festivalorderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='VAT-inclusive combined unit price snapshot (product + addition).', max_digits=10),
        ),
        migrations.AddField(
            model_name='festivalorderitem',
            name='addition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='festival.festivaladdition'),
        ),
        migrations.AddConstraint(
            model_name='festivalorderitem',
            constraint=models.UniqueConstraint(fields=('order', 'product', 'addition'), name='festival_order_item_unique_product_addition'),
        ),
        migrations.AddField(
            model_name='festivaladdition',
            name='addition_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='additions', to='festival.festivaladditionclass'),
        ),
        migrations.AddField(
            model_name='festivalproduct',
            name='addition_class',
            field=models.ForeignKey(blank=True, help_text='Additions from this class can be chosen with the product.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='festival.festivaladditionclass'),
        ),
        migrations.AddConstraint(
            model_name='festivaladdition',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='festival_addition_price_non_negative'),
        ),
    ]
