# Generated by Django 5.2 on 2026-07-22 12:14

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0006_festivaladdition_festivaladditionclass_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FestivalFilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Filling',
                'verbose_name_plural': 'Fillings',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='festivalorderitem',
            name='festival_order_item_unique_product_addition',
        ),
        migrations.AddField(
            model_name='festivalorderitem',
            name='filling_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='festivaladdition',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='VAT-inclusive addition price (default £0.00).', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='festivalfilling',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fillings', to='festival.festivalproduct'),
        ),
        migrations.AddField(
            model_name='festivalorderitem',
            name='filling',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='festival.festivalfilling'),
        ),
        migrations.AddConstraint(
            model_name='festivalorderitem',
            constraint=models.UniqueConstraint(fields=('order', 'product', 'filling', 'addition'), name='festival_order_item_unique_product_filling_addition'),
        ),
        migrations.AddConstraint(
            model_name='festivalfilling',
            constraint=models.UniqueConstraint(fields=('product', 'name'), name='festival_filling_unique_per_product'),
        ),
    ]
