# Generated by Django 5.2 on 2026-07-22 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0007_festivalfilling_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festivalfilling',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fillings', to='festival.festivalproduct'),
        ),
        migrations.AlterField(
            model_name='festivalorderitem',
            name='addition',
            field=models.ForeignKey(blank=True, help_text='May be null if the addition was deleted; use addition_name snapshot.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='festival.festivaladdition'),
        ),
        migrations.AlterField(
            model_name='festivalorderitem',
            name='filling',
            field=models.ForeignKey(blank=True, help_text='May be null if the filling was deleted; use filling_name snapshot.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='festival.festivalfilling'),
        ),
        migrations.AlterField(
            model_name='festivalorderitem',
            name='product',
            field=models.ForeignKey(blank=True, help_text='May be null if the product was deleted; use product_name snapshot.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='festival.festivalproduct'),
        ),
    ]
