# Generated by Django 5.2 on 2026-07-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0008_alter_festivalfilling_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='festivalprintjob',
            name='stale_requeue_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
