# Generated by Django 5.2 on 2026-07-22 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0009_printjob_stale_requeue_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='FestivalPrintBatch',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('has_failed', models.BooleanField(default=False)),
                ('has_progress', models.BooleanField(default=False)),
                ('ready_count', models.PositiveIntegerField(default=0)),
                ('queue_available_at', models.DateTimeField()),
                ('queue_created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_batches', to='festival.festivalprinter')),
            ],
            options={
                'indexes': [models.Index(fields=['printer', 'has_failed', 'ready_count', 'has_progress', 'queue_available_at'], name='festival_batch_claim_idx')],
            },
        ),
    ]
