# Generated by Django 5.2 on 2026-07-23 10:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0010_print_batch_denorm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='festivalcategory',
            options={'ordering': ['created_at', 'id'], 'verbose_name': 'Festival category', 'verbose_name_plural': 'Festival categories'},
        ),
        migrations.AlterModelOptions(
            name='festivalproduct',
            options={'ordering': ['category__created_at', 'category__id', 'created_at', 'id'], 'permissions': [('place_festival_order', 'Can place festival orders'), ('cancel_festival_order', 'Can cancel festival orders')]},
        ),
        migrations.AddField(
            model_name='festivalcategory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='festivalproduct',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
