# Generated by Django 5.2 on 2026-07-29 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0010_print_batch_denorm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festivalprintjob',
            name='job_type',
            field=models.CharField(choices=[('KITCHEN', 'Kitchen'), ('CUSTOMER', 'Customer'), ('KITCHEN_CANCELLATION', 'Kitchen cancellation'), ('CUSTOMER_CREDIT', 'Customer credit'), ('TEST', 'Test page')], max_length=32),
        ),
        migrations.AlterField(
            model_name='festivalprintjob',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='print_jobs', to='festival.festivalorder'),
        ),
    ]
