# Generated by Django 5.2 on 2026-07-23 10:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0011_alter_festivalcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='festivaladdition',
            options={'ordering': ['created_at', 'id'], 'verbose_name': 'Addition', 'verbose_name_plural': 'Additions'},
        ),
        migrations.AddField(
            model_name='festivaladdition',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
