# Generated by Django 5.2 on 2026-07-29 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0011_alter_festivalprintjob_job_type_and_more'),
        ('festival', '0012_alter_festivaladdition_options_and_more'),
    ]

    operations = [
    ]
