# Generated by Django 5.2 on 2026-08-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0013_merge_20260729_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='festivaladdition',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive additions are hidden when creating festival orders.'),
        ),
    ]
