# Generated by Django 5.2 on 2026-08-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0014_festivaladdition_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='FestivalMenuSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('included_meal_offer', models.TextField(blank=True, default='', help_text='Optional banner text (e.g. meal-deal offer) shown on the public menu.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Festival menu settings',
                'verbose_name_plural': 'Festival menu settings',
            },
        ),
        migrations.AddField(
            model_name='festivalproduct',
            name='allergens',
            field=models.TextField(blank=True, default='', help_text='Allergen information for the public menu.'),
        ),
        migrations.AddField(
            model_name='festivalproduct',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Short customer-facing description for the public menu.'),
        ),
        migrations.AddField(
            model_name='festivalproduct',
            name='ingredients',
            field=models.TextField(blank=True, default='', help_text='Ingredient list for the public menu.'),
        ),
        migrations.AddField(
            model_name='festivalproduct',
            name='is_publicly_visible',
            field=models.BooleanField(default=False, help_text='When active, show this product on the public festival menu.'),
        ),
        migrations.AddField(
            model_name='festivalproduct',
            name='portion',
            field=models.CharField(blank=True, default='', help_text='Serving size shown on the public menu (e.g. 6 pieces).', max_length=120),
        ),
        migrations.AddField(
            model_name='festivalproduct',
            name='toppings',
            field=models.TextField(blank=True, default='', help_text='Toppings or sauces available, shown on the public menu.'),
        ),
    ]
