# Generated by Django 5.2 on 2026-08-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0015_public_menu_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festivalproduct',
            name='is_publicly_visible',
            field=models.BooleanField(default=True, help_text='Show this festival product on the public /festival-menu page.'),
        ),
    ]
