# Generated by Django 5.2 on 2026-08-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0016_festivalproduct_public_by_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='festivalfilling',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='Optional image for this filling on the public menu.', max_length=500),
        ),
    ]
