# Generated by Django 5.2 on 2026-09-02 23:03

from django.db import migrations


def set_active_products_public(apps, schema_editor):
    FestivalProduct = apps.get_model("festival", "FestivalProduct")
    FestivalProduct.objects.filter(is_active=True, is_publicly_visible=False).update(
        is_publicly_visible=True
    )


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0017_filling_image_url'),
    ]

    operations = [
        migrations.RunPython(set_active_products_public, migrations.RunPython.noop),
    ]
