# Generated by Django 5.2 on 2026-09-03 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0018_backfill_public_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='festivalfilling',
            name='allergens',
            field=models.TextField(blank=True, default='', help_text='Allergens for this filling variant on the public menu.'),
        ),
        migrations.AddField(
            model_name='festivalfilling',
            name='ingredients',
            field=models.TextField(blank=True, default='', help_text='Ingredients for this filling variant on the public menu.'),
        ),
    ]
