# Generated by Django 5.2 on 2026-09-03 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0019_filling_ingredients_allergens'),
    ]

    operations = [
        migrations.RenameField(
            model_name='festivalfilling',
            old_name='ingredients',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='festivalfilling',
            name='description',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Optional description for this filling on the public menu. Falls back to the product description when empty.',
            ),
        ),
    ]
