# Generated by Django 5.2 on 2026-09-03 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0020_filling_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festivalproduct',
            name='is_publicly_visible',
        ),
    ]
