# Generated by Django 5.2 on 2026-09-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0021_remove_is_publicly_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='festivalcategory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive categories are hidden from the public menu and till.'),
        ),
    ]
