# Generated by Django 5.2 on 2026-09-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0022_festivalcategory_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='festivalprintjob',
            name='payload_binary',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
