# Generated by Django 5.2 on 2026-09-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0023_festivalprintjob_payload_binary'),
    ]

    operations = [
        migrations.AddField(
            model_name='festivalorder',
            name='cash',
            field=models.BooleanField(default=False, help_text='True when the order was paid in cash at the till.'),
        ),
    ]
