# Generated by Django 5.2 on 2026-09-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0024_festivalorder_cash'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='festivalorderitem',
            name='festival_order_item_unique_product_filling_addition',
        ),
        migrations.AddField(
            model_name='festivalorderitem',
            name='portion_size',
            field=models.CharField(choices=[('FULL', 'Full'), ('HALF', 'Half')], default='FULL', help_text='FULL or HALF. Existing orders stay FULL.', max_length=8),
        ),
        migrations.AddField(
            model_name='festivalproduct',
            name='allow_half_portion',
            field=models.BooleanField(default=False, help_text='Offer a half portion at 50% of the meal price. Paid extras keep their own price.'),
        ),
        migrations.AddField(
            model_name='festivalproduct',
            name='half_portion',
            field=models.CharField(blank=True, default='', help_text='Optional half-portion description (e.g. 125g or 3 pieces). Shown only when half portions are enabled.', max_length=120),
        ),
        migrations.AlterField(
            model_name='festivalproduct',
            name='portion',
            field=models.CharField(blank=True, default='', help_text='Full portion description shown on the public menu (e.g. 6 pieces or 250g).', max_length=120),
        ),
        migrations.AddConstraint(
            model_name='festivalorderitem',
            constraint=models.UniqueConstraint(fields=('order', 'product', 'filling', 'addition', 'portion_size'), name='festival_order_item_unique_product_filling_addition_portion'),
        ),
        migrations.AddConstraint(
            model_name='festivalorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('portion_size__in', ['FULL', 'HALF'])), name='festival_order_item_portion_size_valid'),
        ),
    ]
