"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import sys
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(os.path.join(BASE_DIR, "../.env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

_INSECURE_DEFAULT_SECRET_KEY = (
    "django-insecure-+c6w+lxtf*1xscm)4_f#6e5n+xsz4=@r-&08__hli=b!%7v-=9"
)
SECRET_KEY = os.getenv("SECRET_KEY", _INSECURE_DEFAULT_SECRET_KEY)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True") == "True"
if os.getenv("DEBUG") is None:
    # An unset DEBUG means True (debug pages, CORS_ALLOW_ALL_ORIGINS with credentials,
    # non-Secure cookies). Loud on purpose: production must set DEBUG=False explicitly.
    print(
        "WARNING: the DEBUG environment variable is not set - defaulting to DEBUG=True. "
        "Set DEBUG=False in production.",
        file=sys.stderr,
    )

# The fallback above is public (it is in git). Signing JWTs, CSRF/session cookies and
# the auth-log email hashes with it makes them forgeable. Refuse to boot in production.
if not DEBUG and (
    SECRET_KEY == _INSECURE_DEFAULT_SECRET_KEY
    or SECRET_KEY.startswith(("django-insecure-", "change-me"))
):
    raise ImproperlyConfigured(
        "SECRET_KEY is the built-in insecure default or a placeholder while DEBUG is off. "
        "Set a unique SECRET_KEY in the environment (see generate_secret_key.py)."
    )

ALLOWED_HOSTS = os.getenv(
    "ALLOWED_HOSTS", "localhost,127.0.0.1,backend,frontend-marketplace,nginx"
).split(",")

# Proxy settings for HTTPS behind reverse proxy
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "account",
    "api.apps.ApiConfig",
    "storages",
    "billing",
    "shipping",
    "reconciliation",
    "notifications",
    "festival.apps.FestivalConfig",
]

MIDDLEWARE = [
    # First, so every response (CORS pre-flights, errors) carries X-Request-ID.
    "account.observability.RequestIDMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# CSRF/session cookies are Secure (HTTPS only) everywhere except local DEBUG - production
# is HTTPS-only behind Cloudflare/nginx. The SPA reads the csrftoken cookie from
# JavaScript, so it must stay non-HttpOnly.
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = "Lax"

ROOT_URLCONF = "backend.urls"
# Allow Django to append trailing slashes for API consistency
APPEND_SLASH = False
# CORS / CSRF origins - derive from URL_BASE when env overrides are unset.
# When CSRF_TRUSTED_ORIGINS or CORS_ALLOWED_ORIGINS is set, list every real SPA
# origin (scheme + host [+ port]); cookie-based JWT refresh requires CSRF.
URL_BASE = os.getenv("URL_BASE", "https://localhost")


def _default_browser_origins(url_base: str) -> str:
    """Build default CORS/CSRF origins from URL_BASE (no invented domains)."""
    from urllib.parse import urlparse

    base = url_base.rstrip("/")
    origins = [base]
    parsed = urlparse(base)
    host = (parsed.hostname or "").lower()
    # Dev convenience: Next on :3000 when URL_BASE is bare localhost/127.0.0.1.
    if host in ("localhost", "127.0.0.1") and parsed.port != 3000:
        scheme = parsed.scheme or "https"
        origins.append(f"{scheme}://{host}:3000")
    return ",".join(dict.fromkeys(origins))


_default_origins = _default_browser_origins(URL_BASE)
CORS_ALLOWED_ORIGINS = [
    o.strip()
    for o in os.getenv("CORS_ALLOWED_ORIGINS", _default_origins).split(",")
    if o.strip()
]
CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.getenv("CSRF_TRUSTED_ORIGINS", _default_origins).split(",")
    if o.strip()
]

# Additional CORS settings for proper functionality``
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_HEADERS = True
CORS_ALLOWED_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

# Allow all methods for API calls
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

# For development, allow all origins
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True

# Additional CORS settings for debugging
CORS_EXPOSE_HEADERS = [
    "Content-Type",
    "X-CSRFToken",
    "Authorization",
    # Readable by the SPA when it is served from a different origin (dev).
    "X-Request-ID",
    "Retry-After",
]

# Preflight cache time
CORS_PREFLIGHT_MAX_AGE = 86400

# REST Framework settings
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
    ],
    # Behind the nginx reverse proxy the client IP is in X-Forwarded-For.
    # Tell DRF how many trusted proxies sit in front so per-client throttling
    # keys on the real visitor IP instead of the shared nginx address.
    "NUM_PROXIES": int(os.getenv("DRF_NUM_PROXIES", "1")),
    # Friendly 429 bodies + request_id on /api/auth/* errors (account.api_errors).
    "EXCEPTION_HANDLER": "account.api_errors.exception_handler",
}

# Auth throttle rates ("N/second|minute|hour|day"), env-overridable. IP scopes use the
# real client IP (see account.throttles); register/resend also have a hashed-email
# scope so a shared NAT/CF edge cannot lock the next customer out. Read at request
# time; a malformed value falls back to the default. Documented in docs/AUTH_OBSERVABILITY.md.
#
# Per-IP buckets are generous so a launch, office NAT, or a mis-read edge IP cannot
# cap legitimate signups/verifies. Per-address buckets stay tight (abuse, not capacity).
REGISTER_RATE_LIMIT = os.getenv("REGISTER_RATE_LIMIT", "300/hour")
REGISTER_EMAIL_RATE_LIMIT = os.getenv("REGISTER_EMAIL_RATE_LIMIT", "8/hour")
LOGIN_RATE_LIMIT = os.getenv("LOGIN_RATE_LIMIT", "20/minute")
# Per (client IP, email): slows guessing one account's password.
LOGIN_EMAIL_RATE_LIMIT = os.getenv("LOGIN_EMAIL_RATE_LIMIT", "8/minute")
PASSWORD_RESET_RATE_LIMIT = os.getenv("PASSWORD_RESET_RATE_LIMIT", "100/hour")
PASSWORD_RESET_EMAIL_RATE_LIMIT = os.getenv("PASSWORD_RESET_EMAIL_RATE_LIMIT", "8/hour")
EMAIL_VERIFICATION_RATE_LIMIT = os.getenv("EMAIL_VERIFICATION_RATE_LIMIT", "1000/hour")
EMAIL_VERIFICATION_RESEND_RATE_LIMIT = os.getenv(
    "EMAIL_VERIFICATION_RESEND_RATE_LIMIT", "12/hour"
)
EMAIL_VERIFICATION_RESEND_IP_RATE_LIMIT = os.getenv(
    "EMAIL_VERIFICATION_RESEND_IP_RATE_LIMIT", "300/hour"
)
# Browser failure beacon (POST /api/auth/client-event/).
CLIENT_EVENT_RATE_LIMIT = os.getenv("CLIENT_EVENT_RATE_LIMIT", "60/minute")

# JWT Settings
from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUDIENCE": None,
    "ISSUER": None,
    "JWK_URL": None,
    "LEEWAY": 0,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",
    "JTI_CLAIM": "jti",
    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),
}

# Refresh JWT in httpOnly cookie (not readable by XSS). Path limited to auth API.
JWT_REFRESH_COOKIE_NAME = os.getenv("JWT_REFRESH_COOKIE_NAME", "refresh_token")
JWT_REFRESH_COOKIE_PATH = os.getenv("JWT_REFRESH_COOKIE_PATH", "/api/auth/")
JWT_REFRESH_COOKIE_SAMESITE = os.getenv("JWT_REFRESH_COOKIE_SAMESITE", "Lax")
JWT_REFRESH_COOKIE_SECURE = os.getenv(
    "JWT_REFRESH_COOKIE_SECURE",
    "False" if DEBUG else "True",
).lower() in ("1", "true", "yes")
# Seconds a just-rotated refresh token is still honoured, so two tabs refreshing at once
# do not kill the session (account.views.CookieTokenRefreshSerializer). 0 disables.
JWT_REFRESH_ROTATION_GRACE_SECONDS = int(
    os.getenv("JWT_REFRESH_ROTATION_GRACE_SECONDS", "30")
)

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


# PostgreSQL configuration using environment variables
def get_database_config():
    """Get database configuration from environment variables with validation"""
    required_vars = [
        "POSTGRES_DB",
        "POSTGRES_USER",
        "POSTGRES_PASSWORD",
        "POSTGRES_HOST",
    ]
    missing_vars = [var for var in required_vars if not os.getenv(var)]

    if missing_vars:
        raise ValueError(
            f"Missing required environment variables: {', '.join(missing_vars)}"
        )

    # Prefer explicit POSTGRES_HOST if provided, otherwise fall back to Docker service name
    PG_HOST = os.getenv("POSTGRES_HOST", "postgres")

    return {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB"),
        "USER": os.getenv("POSTGRES_USER"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
        "HOST": PG_HOST,
        "PORT": os.getenv("POSTGRES_PORT", "5432"),
        "OPTIONS": {
            "connect_timeout": 5,
        },
        # Reuse connections for 60s; CONN_HEALTH_CHECKS avoids stale sockets.
        "CONN_MAX_AGE": 60,
        "CONN_HEALTH_CHECKS": True,
    }


try:
    DATABASES = {"default": get_database_config()}
    # DATABASES = {
    #     "default": {
    #         "ENGINE": "django.db.backends.sqlite3",
    #         "NAME": BASE_DIR / "db" / "db.sqlite3",
    #     }
    # }
except ValueError as e:
    print(
        f"Database configuration error: {e}\n",
        "Please ensure all required environment variables are set in your .env file",
    )
    # Fallback to SQLite for development if PostgreSQL config is missing
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db" / "db.sqlite3",
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_USER_MODEL = "account.CustomUser"

# Authentication backends
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "account.validators.CustomPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/London"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/


STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATICFILES_STORAGE = "django.contrib.staticfiles.storage.ManifestStaticFilesStorage"


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Cart/order delivery: products in this category can qualify for post (Royal Mail) pricing.
# Post delivery (Royal Mail) uses categories in this CategoryGroup (default: group #1).
POST_DELIVERY_CATEGORY_GROUP_ID = int(os.getenv("POST_DELIVERY_CATEGORY_GROUP_ID", "1"))
# Food summary export: products in this CategoryGroup count as frozen (default: group #2).
FROZEN_CATEGORY_GROUP_ID = int(os.getenv("FROZEN_CATEGORY_GROUP_ID", "2"))

# AWS Configuration

AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME")
AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME")
AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com"

AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None
AWS_QUERYSTRING_AUTH = False

S3_STORAGE_CLASS = os.getenv("S3_STORAGE_CLASS")  # Storage class
S3_BACKUP_DIR = os.getenv("S3_BACKUP_DIR")  # Directory prefix in S3

EMAIL_BACKEND = os.getenv("EMAIL_BACKEND")
AWS_SES_REGION_NAME = os.getenv("AWS_SES_REGION_NAME")
AWS_SES_REGION_ENDPOINT = os.getenv("AWS_SES_REGION_ENDPOINT")
# django-ses default is 0.5: it sleeps in the worker to stay at 50% of the SES
# max-send-rate. That caps throughput and holds Celery slots. Leave it off and
# retry SES throttling via Celery (account.tasks). Set e.g. 0.5 to re-enable.
_raw_ses_auto_throttle = (os.getenv("AWS_SES_AUTO_THROTTLE") or "").strip().lower()
if _raw_ses_auto_throttle in ("", "none", "off", "false", "0"):
    AWS_SES_AUTO_THROTTLE = None
else:
    AWS_SES_AUTO_THROTTLE = float(_raw_ses_auto_throttle)
AWS_SES_CONFIGURATION_SET = (os.getenv("AWS_SES_CONFIGURATION_SET") or "").strip() or None

SUPPORT_FROM_EMAIL = os.getenv("SUPPORT_FROM_EMAIL")
NOREPLY_FROM_EMAIL = os.getenv("NOREPLY_FROM_EMAIL")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")

# optional: one place to define a standard reply-to for system emails
SUPPORT_REPLY_TO = os.getenv("SUPPORT_REPLY_TO")

# Email Authentication
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")

EMAIL_SUBJECT_PREFIX = os.getenv("EMAIL_SUBJECT_PREFIX")

# Email Delivery Settings (SMTP backends only; SES uses boto3 timeouts).
_email_timeout = (os.getenv("EMAIL_TIMEOUT") or "").strip()
EMAIL_TIMEOUT = int(_email_timeout) if _email_timeout else None
EMAIL_USE_LOCALTIME = os.getenv("EMAIL_USE_LOCALTIME", "False").lower() in (
    "1",
    "true",
    "yes",
)

# AWS S3 Media files storage
DEFAULT_FILE_STORAGE = os.getenv("DEFAULT_FILE_STORAGE")
MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/"

# Cloudflare R2 Configuration (for product images)
R2_ACCESS_KEY_ID = os.getenv("R2_ACCESS_KEY_ID")
R2_SECRET_ACCESS_KEY = os.getenv("R2_SECRET_ACCESS_KEY")
R2_BUCKET_NAME = os.getenv("R2_BUCKET_NAME")
R2_ACCOUNT_ID = os.getenv("R2_ACCOUNT_ID")
R2_ENDPOINT_URL = f"https://{R2_ACCOUNT_ID}.r2.cloudflarestorage.com"
R2_PUBLIC_URL = os.getenv("R2_PUBLIC_URL")  # Your R2 custom domain or public URL

# Product Image Settings
ALLOWED_IMAGE_TYPES = ["image/jpeg", "image/jpg", "image/png", "image/webp"]
MAX_IMAGE_SIZE = 5 * 1024 * 1024  # 5MB in bytes
PRESIGNED_URL_EXPIRATION = 300  # 5 minutes

# File Upload Settings - Allow larger file uploads for admin panel
DATA_UPLOAD_MAX_MEMORY_SIZE = (
    10 * 1024 * 1024
)  # 10MB - files larger than this use temp files
FILE_UPLOAD_MAX_MEMORY_SIZE = (
    10 * 1024 * 1024
)  # 10MB - files larger than this use temp files
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000  # Increase if needed for complex forms

BUSINESS_INFO = {
    "name": os.getenv("BUSINESS_NAME", "My Business name"),
    "address": os.getenv("BUSINESS_ADDRESS", "Address"),
    "city": os.getenv("BUSINESS_CITY", "City"),
    "country": os.getenv("BUSINESS_COUNTRY", "Country"),
    "postal_code": os.getenv("BUSINESS_POSTAL_CODE", "Postal_Code"),
    "account_name": os.getenv("BUSINESS_ACCOUNT_NAME", "Account Name"),
    "account_number": os.getenv("BUSINESS_ACCOUNT_NUMBER", "Account Number"),
    "sort_code": os.getenv("BUSINESS_SORT_CODE", "Sort Code"),
    "invoice_code": os.getenv("INVOICE_CODE", ""),
    "tax_code": os.getenv("TAX_CODE", ""),
}

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Password Reset Settings
# Reset emails are queued through Celery/SES, so 15 minutes was tight (the email itself
# promises 1 hour). Env-overridable; read by PasswordResetToken and Django's token generator.
PASSWORD_RESET_TIMEOUT = int(os.getenv("PASSWORD_RESET_TIMEOUT", "3600"))
PASSWORD_RESET_COOLDOWN = 60  # 1 minute cooldown between requests
# (auth throttle rates live in the "Auth throttle rates" block next to REST_FRAMEWORK)

# Email Verification Settings
EMAIL_VERIFICATION_TIMEOUT = 86400  # 24 hours in seconds
EMAIL_VERIFICATION_COOLDOWN = 60  # 1 minute cooldown between resend requests

# Stripe Configuration
STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY", "")
STRIPE_PUBLISHABLE_KEY = os.getenv("STRIPE_PUBLISHABLE_KEY", "")
STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET", "")

# Sendcloud Configuration
SENDCLOUD_PUBLIC_KEY = os.getenv("SENDCLOUD_PUBLIC_KEY", "")
SENDCLOUD_SECRET_KEY = os.getenv("SENDCLOUD_SECRET_KEY", "")
# If the API returns HTTP 412 "User not allowed to announce", complete Sendcloud
# onboarding (panel shipment + carrier activation) and use keys that may announce.
SENDCLOUD_SENDER_COUNTRY = os.getenv("SENDCLOUD_SENDER_COUNTRY", "GB")
SENDCLOUD_SENDER_POSTAL_CODE = os.getenv("SENDCLOUD_SENDER_POSTAL_CODE", "")
SENDCLOUD_WEBHOOK_SECRET = os.getenv("SENDCLOUD_WEBHOOK_SECRET", "")

# Sendcloud Shipping Options Filtering
# Only show specific carriers and services
SENDCLOUD_ALLOWED_CARRIERS = os.getenv(
    "SENDCLOUD_ALLOWED_CARRIERS", "royal_mailv2"
).split(",")
# Service name substrings (lowercase) on Sendcloud method rows. Include Tracked 24 so
# ``uk_tracked_24`` can resolve (exclude list must not blanket-ban ``tracked 24``).
# Tracked 48 may remain listed for legacy method-name matching.
SENDCLOUD_ALLOWED_SERVICES = os.getenv(
    "SENDCLOUD_ALLOWED_SERVICES", "tracked 48,tracked 24"
).split(",")
SENDCLOUD_EXCLUDE_SERVICES = os.getenv(
    "SENDCLOUD_EXCLUDE_SERVICES", "signed,express,large letter"
).split(",")

# Sendcloud panel sender address (integer ID). Required for post-delivery shipment automation.
SENDCLOUD_SENDER_ADDRESS_ID = os.getenv("SENDCLOUD_SENDER_ADDRESS_ID") or None
# Logical option → resolved at ship time via /shipping_methods (IDs must not be stored long-term).
# When POST_SHIPMENT_USE_WEIGHT_BASED_LOGICAL is True (default), checkout/ship always use
# uk_tracked_24 (weight only picks the small/medium tier). Otherwise this single value is used.
POST_SHIPMENT_LOGICAL_OPTION = os.getenv(
    "POST_SHIPMENT_LOGICAL_OPTION", "uk_tracked_24"
)
POST_SHIPMENT_USE_WEIGHT_BASED_LOGICAL = os.getenv(
    "POST_SHIPMENT_USE_WEIGHT_BASED_LOGICAL", "True"
).lower() in ("1", "true", "yes")
# Legacy: previously switched Tracked 48 vs 24 by weight. Ignored — always Tracked 24.
_post_t24 = (os.getenv("POST_SHIPMENT_TRACKED_24_MIN_KG") or "").strip()
POST_SHIPMENT_TRACKED_24_MIN_KG = float(_post_t24) if _post_t24 else None
# Post-delivery cart/order fee estimate when no delivery address: Sendcloud price × markup.
POST_DELIVERY_SENDCLOUD_MARKUP_PERCENT = float(
    os.getenv("POST_DELIVERY_SENDCLOUD_MARKUP_PERCENT", "20")
)
POST_DELIVERY_ESTIMATE_COUNTRY = (
    os.getenv("POST_DELIVERY_ESTIMATE_COUNTRY", "GB").strip() or "GB"
)
POST_DELIVERY_ESTIMATE_POSTAL_CODE = (
    os.getenv("POST_DELIVERY_ESTIMATE_POSTAL_CODE", "SW1A 1AA").strip() or "SW1A 1AA"
)
# Prefix for Sendcloud parcel ``order_number``: {prefix}-{order_id}-{random10digits}.
SENDCLOUD_ORDER_NUMBER_PREFIX = os.getenv("SENDCLOUD_ORDER_NUMBER_PREFIX", "FP")
# Sendcloud recommends refreshing shipping method IDs at least hourly.
SENDCLOUD_METHODS_CACHE_TTL = int(os.getenv("SENDCLOUD_METHODS_CACHE_TTL", "3600"))
# Shorter cache for Celery parcel tasks (still uses live API as source of truth).
SENDCLOUD_METHODS_TASK_CACHE_TTL = int(
    os.getenv("SENDCLOUD_METHODS_TASK_CACHE_TTL", "180")
)

# Serialize Celery runs per shipment (duplicate tasks / retries / crashes after remote create).
SENDCLOUD_SHIPMENT_TASK_LOCK_TTL = int(
    os.getenv("SENDCLOUD_SHIPMENT_TASK_LOCK_TTL", "900")
)

# Ideal Postcodes — UK Address Cleanse (https://docs.ideal-postcodes.co.uk/docs/api/address-cleanse)
IDEAL_POSTCODES_API_KEY = (os.getenv("IDEAL_POSTCODES_API_KEY") or "").strip() or None
IDEAL_POSTCODES_ENABLED = os.getenv("IDEAL_POSTCODES_ENABLED", "True").lower() in (
    "1",
    "true",
    "yes",
)
IDEAL_POSTCODES_CLEANSE_MIN_CONFIDENCE = float(
    os.getenv("IDEAL_POSTCODES_CLEANSE_MIN_CONFIDENCE", "0.72")
)
IDEAL_POSTCODES_BASE_URL = (
    os.getenv("IDEAL_POSTCODES_BASE_URL", "https://api.ideal-postcodes.co.uk")
    .strip()
    .rstrip("/")
)
IDEAL_POSTCODES_REQUEST_TIMEOUT = int(
    os.getenv("IDEAL_POSTCODES_REQUEST_TIMEOUT", "15")
)

# Celery (Sendcloud post shipments and other async work)
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://127.0.0.1:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", CELERY_BROKER_URL)
CELERY_TASK_ACCEPT_CONTENT = ["json"]
CELERY_RESULT_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TASK_TIME_LIMIT = 300
CELERY_TASK_SOFT_TIME_LIMIT = 240
# Celery 6: startup broker retries are controlled separately from broker_connection_retry.
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = os.getenv(
    "CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP", "true"
).lower() in ("1", "true", "yes")
# Fail fast on Redis hang so request-path .delay() cannot block signup for minutes.
CELERY_BROKER_TRANSPORT_OPTIONS = {
    "socket_connect_timeout": float(
        os.getenv("CELERY_BROKER_SOCKET_CONNECT_TIMEOUT", "2")
    ),
    "socket_timeout": float(os.getenv("CELERY_BROKER_SOCKET_TIMEOUT", "3")),
}
CELERY_RESULT_EXPIRES = 3600  # 1 hour - prevent Redis result buildup
# Safe: no code reads AsyncResult; festival tasks already use ignore_result=True.
CELERY_TASK_IGNORE_RESULT = True
# One reserved task per worker process so a slow SES call cannot hide a backlog.
CELERY_WORKER_PREFETCH_MULTIPLIER = int(
    os.getenv("CELERY_WORKER_PREFETCH_MULTIPLIER", "1")
)
# Transactional mail on a dedicated queue so festival/print work cannot starve it.
CELERY_TASK_DEFAULT_QUEUE = "celery"
CELERY_TASK_ROUTES = {
    "account.tasks.send_verification_email_task": {"queue": "email"},
    "account.tasks.send_verification_confirmation_email_task": {"queue": "email"},
    "account.tasks.send_password_reset_email_task": {"queue": "email"},
    "account.tasks.send_password_reset_confirmation_email_task": {"queue": "email"},
}
# Compose: celery-email worker consumes this queue. Beat alerts when it backs up.
EMAIL_QUEUE_NAME = os.getenv("EMAIL_QUEUE_NAME", "email")
EMAIL_QUEUE_BACKLOG_ALERT = int(os.getenv("EMAIL_QUEUE_BACKLOG_ALERT", "100"))

# Shared cache (set in Docker to Redis so Gunicorn + Celery see the same keys, e.g. Sendcloud locks).
_django_cache_redis_url = (os.getenv("DJANGO_CACHE_REDIS_URL") or "").strip()
if _django_cache_redis_url:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": _django_cache_redis_url,
            # Django passes OPTIONS to redis-py's ConnectionPool. Without socket timeouts a
            # stalled Redis blocks every cache call - including the auth throttle check on
            # each login/register - until the OS gives up (gunicorn allows 300 s).
            "OPTIONS": {
                "socket_connect_timeout": float(
                    os.getenv("DJANGO_CACHE_SOCKET_CONNECT_TIMEOUT", "2")
                ),
                "socket_timeout": float(os.getenv("DJANGO_CACHE_SOCKET_TIMEOUT", "2")),
            },
        }
    }


# Frontend URL for email verification links - derive from URL_BASE.
# Production must set FRONTEND_URL to the public origin (e.g. https://landarsfood.com).
# Localhost values with DEBUG=False are logged as errors by get_public_frontend_base_url.
def get_frontend_url():
    """Get frontend URL from URL_BASE environment variable"""
    return os.getenv("URL_BASE", "https://localhost")


FRONTEND_URL = os.getenv("FRONTEND_URL", get_frontend_url())

# Public site URL for admin links in notifications (defaults to URL_BASE).
SITE_URL = os.getenv("SITE_URL", URL_BASE).rstrip("/")

# Telegram admin order alerts
TELEGRAM_BOT_TOKEN = (os.getenv("TELEGRAM_BOT_TOKEN") or "").strip()
TELEGRAM_ADMIN_CHAT_ID = (os.getenv("TELEGRAM_ADMIN_CHAT_ID") or "").strip()
TELEGRAM_ORDER_ALERTS_ENABLED = os.getenv(
    "TELEGRAM_ORDER_ALERTS_ENABLED", "false"
).lower() in ("true", "1", "yes")
TELEGRAM_ORDER_ALERTS_TIMEOUT_SECONDS = int(
    os.getenv("TELEGRAM_ORDER_ALERTS_TIMEOUT_SECONDS", "10")
)

# Festival ordering (staff till + CloudPRNT remote printing)
FESTIVAL_ENABLED = os.getenv("FESTIVAL_ENABLED", "false").lower() in (
    "1",
    "true",
    "yes",
)
FESTIVAL_PRINT_MODE = os.getenv("FESTIVAL_PRINT_MODE", "disabled").strip().lower()
if FESTIVAL_PRINT_MODE not in ("disabled", "cloudprnt"):
    FESTIVAL_PRINT_MODE = "disabled"
# Deprecated: orders are always accepted when FESTIVAL_ENABLED. Kept so existing
# env files do not break; neither setting gates place-order any more.
FESTIVAL_PRINTER_REQUIRED = os.getenv("FESTIVAL_PRINTER_REQUIRED", "false").lower() in (
    "1",
    "true",
    "yes",
)
FESTIVAL_ALLOW_ORDERS_WHEN_PRINTER_OFFLINE = os.getenv(
    "FESTIVAL_ALLOW_ORDERS_WHEN_PRINTER_OFFLINE", "true"
).lower() in ("1", "true", "yes")
FESTIVAL_PRINTER_STALE_SECONDS = int(os.getenv("FESTIVAL_PRINTER_STALE_SECONDS", "60"))
# After order placement, wait this long then alert if tickets are still unprinted.
FESTIVAL_PRINT_VERIFY_SECONDS = int(os.getenv("FESTIVAL_PRINT_VERIFY_SECONDS", "90"))
FESTIVAL_CLOUDPRNT_ENDPOINT = os.getenv(
    "FESTIVAL_CLOUDPRNT_ENDPOINT", "/api/festival/cloudprnt/"
)
FESTIVAL_CLOUDPRNT_POLL_SECONDS = int(os.getenv("FESTIVAL_CLOUDPRNT_POLL_SECONDS", "2"))
# 76mm printable width ≈ 42 cols at Star Font A (~1.5mm/char). Override via env.
FESTIVAL_TICKET_COLUMNS = int(os.getenv("FESTIVAL_TICKET_COLUMNS", "42"))
FESTIVAL_TICKET_MAX_BYTES = int(os.getenv("FESTIVAL_TICKET_MAX_BYTES", "32768"))
# CloudPRNT job payload format: markup (Star Document Markup + CPUtil →
# StarPRNT) or plain (Unicode in DB, CP437 on the wire). If markup is set but
# cputil is missing, the process forces plain so orders still print.
FESTIVAL_CLOUDPRNT_JOB_FORMAT = os.getenv(
    "FESTIVAL_CLOUDPRNT_JOB_FORMAT", "markup"
).strip().lower()
if FESTIVAL_CLOUDPRNT_JOB_FORMAT not in ("markup", "plain"):
    FESTIVAL_CLOUDPRNT_JOB_FORMAT = "markup"
FESTIVAL_CPUTIL_PATH = os.getenv(
    "FESTIVAL_CPUTIL_PATH", "/opt/star/cputil/cputil"
).strip()
FESTIVAL_CPUTIL_TIMEOUT_SECONDS = float(
    os.getenv("FESTIVAL_CPUTIL_TIMEOUT_SECONDS", "5")
)
# Wire encoding for CloudPRNT text/plain GET (plain mode / plain fallback).
# Default cp437 so £ prints on Star std code page.
FESTIVAL_TICKET_ENCODING = os.getenv("FESTIVAL_TICKET_ENCODING", "cp437").strip()
FESTIVAL_MAX_ITEM_QUANTITY = int(os.getenv("FESTIVAL_MAX_ITEM_QUANTITY", "99"))
FESTIVAL_CLOUDPRNT_USERNAME = os.getenv("FESTIVAL_CLOUDPRNT_USERNAME", "festival-printer")
FESTIVAL_CLOUDPRNT_PASSWORD = os.getenv("FESTIVAL_CLOUDPRNT_PASSWORD", "")
FESTIVAL_VAT_REGISTERED = os.getenv("FESTIVAL_VAT_REGISTERED", "false").lower() in (
    "1",
    "true",
    "yes",
)
# Festival documents reuse BUSINESS_INFO["tax_code"] (TAX_CODE env) as the VAT
# number, the same source as the main invoice/credit-note system.
FESTIVAL_ORDER_PREFIX = os.getenv("FESTIVAL_ORDER_PREFIX", "FEST")
FESTIVAL_INVOICE_PREFIX = os.getenv("FESTIVAL_INVOICE_PREFIX", "FINV")
FESTIVAL_CREDIT_NOTE_PREFIX = os.getenv("FESTIVAL_CREDIT_NOTE_PREFIX", "FCN")

# Celery Beat: festival recovery (optional; used when celery-beat service runs)
from celery.schedules import crontab  # noqa: E402

CELERY_BEAT_SCHEDULE = {
    "festival-recover-stale-claims": {
        "task": "festival.tasks.recover_stale_festival_print_claims",
        "schedule": crontab(minute="*/5"),
    },
    "festival-printer-health": {
        "task": "festival.tasks.check_festival_printer_health",
        "schedule": crontab(minute="*/5"),
    },
    "festival-missing-pdfs": {
        "task": "festival.tasks.report_missing_festival_document_pdfs",
        "schedule": crontab(minute=15),
    },
    "festival-cleanup-ticket-payloads": {
        "task": "festival.tasks.cleanup_old_festival_ticket_payloads",
        "schedule": crontab(hour=3, minute=30),
    },
    "auth-cleanup-expired-tokens": {
        "task": "account.tasks.cleanup_expired_auth_tokens_task",
        "schedule": crontab(hour=4, minute=15),
    },
    "auth-alert-unsent-verification-emails": {
        "task": "account.tasks.alert_unsent_verification_emails_task",
        "schedule": crontab(minute="*/10"),
    },
    "auth-alert-email-queue-backlog": {
        "task": "account.tasks.alert_email_queue_backlog_task",
        "schedule": crontab(minute="*/2"),
    },
}

# Optional persistent copy of the auth event stream (JSON lines, 10 MB x 10 files).
# docker's json-file driver only keeps 3 x 10 MB per container; point this at a mounted
# volume (e.g. /backend/logs/auth_events.log) for longer retention. See
# docs/AUTH_OBSERVABILITY.md. Unusable paths are skipped with a warning, never fatal.
_auth_event_log_file = (os.getenv("AUTH_EVENT_LOG_FILE") or "").strip()
if _auth_event_log_file:
    try:
        _auth_event_log_dir = os.path.dirname(os.path.abspath(_auth_event_log_file))
        os.makedirs(_auth_event_log_dir, exist_ok=True)
        if not os.access(_auth_event_log_dir, os.W_OK):
            raise OSError("directory is not writable")
    except OSError as _exc:
        print(
            f"WARNING: AUTH_EVENT_LOG_FILE ignored ({_exc}); auth events go to stdout only.",
            file=sys.stderr,
        )
        _auth_event_log_file = ""

# Text log lines: timestamp with UTC offset (TIME_ZONE is Europe/London, so plain
# asctime would be ambiguous), level, logger, request id ("-" outside a request).
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {
            # Scrubs emails/JWTs out of tracebacks (driver errors quote the offending value).
            "()": "account.observability.ScrubbingFormatter",
            "format": "{asctime} {levelname} {name} rid={request_id} {message}",
            "datefmt": "%Y-%m-%dT%H:%M:%S%z",
            "style": "{",
        },
        # One JSON object per line, message only (account.observability.log_auth_event).
        "auth_event": {
            "()": "account.observability.AuthEventFormatter",
        },
    },
    "filters": {
        # Star CloudPRNT probes without Authorization, gets 401 + WWW-Authenticate,
        # then retries with Basic auth. Suppress only that expected challenge.
        "suppress_cloudprnt_auth_challenge": {
            "()": "festival.logging_filters.SuppressCloudPRNTAuthChallenge",
        },
        # Provides %(request_id)s to the "simple" formatter.
        "request_id": {
            "()": "account.observability.RequestIDLogFilter",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
            "filters": ["request_id"],
        },
        "console_django_request": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
            "filters": ["request_id", "suppress_cloudprnt_auth_challenge"],
        },
        "auth_events_console": {
            "class": "logging.StreamHandler",
            "stream": "ext://sys.stdout",
            "formatter": "auth_event",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    # Suppress fonttools verbose logging
    "loggers": {
        "fontTools": {
            "level": "ERROR",
            "propagate": False,
        },
        "fontTools.subset": {
            "level": "ERROR",
            "propagate": False,
        },
        "weasyprint": {
            "level": "ERROR",
            "propagate": False,
        },
        # Quiet healthy Celery ticks; failures/exceptions still surface.
        # Festival beat tasks only emit app WARNING/INFO when counts > 0.
        "celery.app.trace": {
            "level": "WARNING",
            "propagate": False,
        },
        "celery.worker.strategy": {
            "level": "WARNING",
            "propagate": False,
        },
        # Scanner traffic with bogus Host headers — Django already returns 400.
        "django.security.DisallowedHost": {
            "level": "CRITICAL",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console_django_request"],
            "level": "WARNING",
            "propagate": False,
        },
        # Structured auth events (account.observability.log_auth_event): JSON lines on
        # stdout only - they must not be duplicated into the text console log.
        "account.auth": {
            "handlers": ["auth_events_console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

if _auth_event_log_file:
    LOGGING["handlers"]["auth_events_file"] = {
        "class": "logging.handlers.RotatingFileHandler",
        "filename": _auth_event_log_file,
        "maxBytes": 10 * 1024 * 1024,
        "backupCount": 10,
        "encoding": "utf-8",
        "delay": True,
        "formatter": "auth_event",
    }
    LOGGING["loggers"]["account.auth"]["handlers"].append("auth_events_file")
