"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(os.path.join(BASE_DIR, "../.env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = os.getenv(
    "SECRET_KEY", "django-insecure-+c6w+lxtf*1xscm)4_f#6e5n+xsz4=@r-&08__hli=b!%7v-=9"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True") == "True"

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "localhost").split(",")

# Proxy settings for HTTPS behind reverse proxy
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "account",
    "api",
    "storages",
    "shipping",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# Disable CSRF for API endpoints in development
if DEBUG:
    CSRF_COOKIE_SECURE = False
    CSRF_COOKIE_HTTPONLY = False
    CSRF_COOKIE_SAMESITE = "Lax"

ROOT_URLCONF = "backend.urls"
# Allow Django to append trailing slashes for API consistency
APPEND_SLASH = False
# CORS settings - derive from URL_BASE for email links
URL_BASE = os.getenv("URL_BASE", "https://localhost")

# Generate CORS origins from URL_BASE
cors_origins = f"{URL_BASE}:3000"
CORS_ALLOWED_ORIGINS = os.getenv("CORS_ALLOWED_ORIGINS", cors_origins).split(",")
CSRF_TRUSTED_ORIGINS = os.getenv("CSRF_TRUSTED_ORIGINS", cors_origins).split(",")

# Additional CORS settings for proper functionality``
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_HEADERS = True
CORS_ALLOWED_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

# Allow all methods for API calls
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

# For development, allow all origins
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True

# Additional CORS settings for debugging
CORS_EXPOSE_HEADERS = [
    "Content-Type",
    "X-CSRFToken",
    "Authorization",
]

# Preflight cache time
CORS_PREFLIGHT_MAX_AGE = 86400

# REST Framework settings
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
    ],
}

# JWT Settings
from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUDIENCE": None,
    "ISSUER": None,
    "JWK_URL": None,
    "LEEWAY": 0,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",
    "JTI_CLAIM": "jti",
    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),
}

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


# PostgreSQL configuration using environment variables
def get_database_config():
    """Get database configuration from environment variables with validation"""
    required_vars = [
        "POSTGRES_DB",
        "POSTGRES_USER",
        "POSTGRES_PASSWORD",
        "POSTGRES_HOST",
    ]
    missing_vars = [var for var in required_vars if not os.getenv(var)]

    if missing_vars:
        raise ValueError(
            f"Missing required environment variables: {', '.join(missing_vars)}"
        )

    # Prefer explicit POSTGRES_HOST if provided, otherwise fall back to Docker service name
    PG_HOST = os.getenv("POSTGRES_HOST", "postgres")

    return {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB"),
        "USER": os.getenv("POSTGRES_USER"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
        "HOST": PG_HOST,
        "PORT": os.getenv("POSTGRES_PORT", "5432"),
        "OPTIONS": {
            "connect_timeout": 10,
        },
    }


try:
    DATABASES = {"default": get_database_config()}
    # DATABASES = {
    #     "default": {
    #         "ENGINE": "django.db.backends.sqlite3",
    #         "NAME": BASE_DIR / "db" / "db.sqlite3",
    #     }
    # }
except ValueError as e:
    print(
        f"Database configuration error: {e}\n",
        "Please ensure all required environment variables are set in your .env file",
    )
    # Fallback to SQLite for development if PostgreSQL config is missing
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db" / "db.sqlite3",
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_USER_MODEL = "account.CustomUser"

# Authentication backends
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/London"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/


STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATICFILES_STORAGE = "django.contrib.staticfiles.storage.ManifestStaticFilesStorage"


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


SAUSAGE_ONLY_MODE = True

# AWS Configuration

AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME")
AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME")
AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com"

AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None
AWS_QUERYSTRING_AUTH = False

S3_STORAGE_CLASS = os.getenv("S3_STORAGE_CLASS")  # Storage class
S3_BACKUP_DIR = os.getenv("S3_BACKUP_DIR")  # Directory prefix in S3

EMAIL_BACKEND = os.getenv("EMAIL_BACKEND")
AWS_SES_REGION_NAME = os.getenv("AWS_SES_REGION_NAME")
AWS_SES_REGION_ENDPOINT = os.getenv("AWS_SES_REGION_ENDPOINT")

SUPPORT_FROM_EMAIL = os.getenv("SUPPORT_FROM_EMAIL")
NOREPLY_FROM_EMAIL = os.getenv("NOREPLY_FROM_EMAIL")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")

# optional: one place to define a standard reply-to for system emails
SUPPORT_REPLY_TO = os.getenv("SUPPORT_REPLY_TO")

# Email Authentication
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")

EMAIL_SUBJECT_PREFIX = os.getenv("EMAIL_SUBJECT_PREFIX")

# Email Delivery Settings
EMAIL_TIMEOUT = os.getenv("EMAIL_TIMEOUT")
EMAIL_USE_LOCALTIME = os.getenv("EMAIL_USE_LOCALTIME")

# AWS S3 Media files storage
DEFAULT_FILE_STORAGE = os.getenv("DEFAULT_FILE_STORAGE")
MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/"

# Cloudflare R2 Configuration (for product images)
R2_ACCESS_KEY_ID = os.getenv("R2_ACCESS_KEY_ID")
R2_SECRET_ACCESS_KEY = os.getenv("R2_SECRET_ACCESS_KEY")
R2_BUCKET_NAME = os.getenv("R2_BUCKET_NAME")
R2_ACCOUNT_ID = os.getenv("R2_ACCOUNT_ID")
R2_ENDPOINT_URL = f"https://{R2_ACCOUNT_ID}.r2.cloudflarestorage.com"
R2_PUBLIC_URL = os.getenv("R2_PUBLIC_URL")  # Your R2 custom domain or public URL

# Product Image Settings
ALLOWED_IMAGE_TYPES = ["image/jpeg", "image/jpg", "image/png", "image/webp"]
MAX_IMAGE_SIZE = 5 * 1024 * 1024  # 5MB in bytes
PRESIGNED_URL_EXPIRATION = 300  # 5 minutes

# File Upload Settings - Allow larger file uploads for admin panel
DATA_UPLOAD_MAX_MEMORY_SIZE = (
    10 * 1024 * 1024
)  # 10MB - files larger than this use temp files
FILE_UPLOAD_MAX_MEMORY_SIZE = (
    10 * 1024 * 1024
)  # 10MB - files larger than this use temp files
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000  # Increase if needed for complex forms

BUSINESS_INFO = {
    "name": os.getenv("BUSINESS_NAME", "My Business name"),
    "address": os.getenv("BUSINESS_ADDRESS", "Address"),
    "city": os.getenv("BUSINESS_CITY", "City"),
    "country": os.getenv("BUSINESS_COUNTRY", "Country"),
    "postal_code": os.getenv("BUSINESS_POSTAL_CODE", "Postal_Code"),
    "account_name": os.getenv("BUSINESS_ACCOUNT_NAME", "Account Name"),
    "account_number": os.getenv("BUSINESS_ACCOUNT_NUMBER", "Account Number"),
    "sort_code": os.getenv("BUSINESS_SORT_CODE", "Sort Code"),
}

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Password Reset Settings
PASSWORD_RESET_TIMEOUT = 900  # 15 minutes in seconds (enhanced security)
PASSWORD_RESET_COOLDOWN = 60  # 1 minute cooldown between requests

# Rate limiting for password reset
PASSWORD_RESET_RATE_LIMIT = "5/hour"  # 5 requests per hour per IP
PASSWORD_RESET_EMAIL_RATE_LIMIT = "3/hour"

# Email Verification Settings
EMAIL_VERIFICATION_TIMEOUT = 86400  # 24 hours in seconds
EMAIL_VERIFICATION_COOLDOWN = 60  # 1 minute cooldown between resend requests
EMAIL_VERIFICATION_RATE_LIMIT = "5/hour"  # 5 verification requests per hour per IP
EMAIL_VERIFICATION_RESEND_RATE_LIMIT = "3/hour"  # 3 resend requests per hour per IP

# Stripe Configuration
STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY", "")
STRIPE_PUBLISHABLE_KEY = os.getenv("STRIPE_PUBLISHABLE_KEY", "")
STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET", "")

# Sendcloud Configuration
SENDCLOUD_PUBLIC_KEY = os.getenv("SENDCLOUD_PUBLIC_KEY", "")
SENDCLOUD_SECRET_KEY = os.getenv("SENDCLOUD_SECRET_KEY", "")
SENDCLOUD_SENDER_COUNTRY = os.getenv("SENDCLOUD_SENDER_COUNTRY", "GB")
SENDCLOUD_SENDER_POSTAL_CODE = os.getenv("SENDCLOUD_SENDER_POSTAL_CODE", "")

# Sendcloud Shipping Options Filtering
# Only show specific carriers and services
SENDCLOUD_ALLOWED_CARRIERS = os.getenv(
    "SENDCLOUD_ALLOWED_CARRIERS", "royal_mail,royal_mailv2"
).split(",")
SENDCLOUD_ALLOWED_SERVICES = os.getenv(
    "SENDCLOUD_ALLOWED_SERVICES", "tracked 48"
).split(",")
SENDCLOUD_EXCLUDE_SERVICES = os.getenv(
    "SENDCLOUD_EXCLUDE_SERVICES", "signed,tracked 24,express,large letter"
).split(",")


# Frontend URL for email verification links - derive from URL_BASE
def get_frontend_url():
    """Get frontend URL from URL_BASE environment variable"""
    return os.getenv("URL_BASE", "https://localhost")


FRONTEND_URL = os.getenv("FRONTEND_URL", get_frontend_url())

# Simple logging configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}
