# Generated by Django 5.2 on 2026-04-01 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0043_order_sendcloud_billable_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Checkout (no courier snapshot yet)'), ('pending', 'Pending (snapshot)'), ('queued', 'Queued'), ('creating', 'Creating'), ('label_download_pending', 'Label download pending'), ('label_download_failed', 'Label download failed'), ('label_ready', 'Label file ready'), ('failed_retryable', 'Failed (retryable)'), ('failed_final', 'Failed (final)'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=32)),
                ('shipping_method_id', models.IntegerField(blank=True, help_text='Sendcloud method id from checkout (used when still valid for route/weight).', null=True)),
                ('sendcloud_inputs', models.JSONField(default=dict, help_text='Frozen parcel-creation payload: address_snapshot, item_lines_snapshot, logical_shipping_option, total_weight_kg, total_order_value, total_item_quantity, sender_address_id, sendcloud_order_reference (strings/decimals as JSON).')),
                ('sendcloud_parcel_id', models.BigIntegerField(blank=True, db_index=True, help_text='Sendcloud parcel id after POST /parcels.', null=True)),
                ('carrier_code', models.CharField(blank=True, default='', help_text='Carrier code from Sendcloud (tracking URL fallback).', max_length=64)),
                ('provider_label_url', models.URLField(blank=True, default='', help_text='Sendcloud label PDF URL (download). Exposed on order API as shipping_label_url.', max_length=600)),
                ('shipping_tracking_number', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_tracking_url', models.URLField(blank=True, max_length=600, null=True)),
                ('label_s3_key', models.CharField(blank=True, default='', help_text='S3 key for stored label PDF.', max_length=512)),
                ('last_error', models.TextField(blank=True, help_text='Last pipeline / API error (cleared on success).')),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_details', to='api.order')),
            ],
            options={
                'db_table': 'shipping_shipment',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='shipping_sh_status_crtd_idx')],
            },
        ),
    ]
