# Generated by Django 5.2 on 2025-12-10 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0034_remove_order_sendcloud_parcel_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_method_id', models.IntegerField(blank=True, help_text='Sendcloud shipping method ID', null=True)),
                ('shipping_carrier', models.CharField(blank=True, help_text='Shipping carrier name (e.g., DPD, Royal Mail)', max_length=100, null=True)),
                ('shipping_service_name', models.CharField(blank=True, help_text='Shipping service name (e.g., Standard, Express)', max_length=100, null=True)),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost of shipping charged to customer', max_digits=10, null=True)),
                ('shipping_tracking_number', models.CharField(blank=True, help_text='Shipment tracking number', max_length=255, null=True)),
                ('shipping_tracking_url', models.URLField(blank=True, help_text='Shipment tracking URL', max_length=500, null=True)),
                ('shipping_label_url', models.URLField(blank=True, help_text='Shipping label URL', max_length=500, null=True)),
                ('sendcloud_parcel_id', models.IntegerField(blank=True, help_text='Sendcloud parcel ID for tracking', null=True)),
                ('shipping_status', models.CharField(blank=True, choices=[('pending_shipment', 'Pending Shipment'), ('label_created', 'Label Created'), ('shipment_failed', 'Shipment Failed'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered')], help_text='Current shipping status', max_length=50, null=True)),
                ('shipping_error_message', models.TextField(blank=True, help_text='Error message if shipment creation failed', null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_details', to='api.order')),
            ],
        ),
    ]
