# Generated by Django 5.2 on 2026-04-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='When the parcel was delivered (from Sendcloud when available).', null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='expected_delivery_date',
            field=models.DateField(blank=True, help_text='Carrier / Sendcloud expected delivery date when provided.', null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='sendcloud_carrier_status_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Sendcloud parcel status id (webhook / API).', null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='sendcloud_carrier_status_message',
            field=models.CharField(blank=True, default='', help_text='Sendcloud parcel status message (human-readable).', max_length=512),
        ),
        migrations.AddField(
            model_name='shipment',
            name='sendcloud_last_webhook_at',
            field=models.DateTimeField(blank=True, help_text='Time of the last applied Sendcloud parcel webhook (ordering stale events).', null=True),
        ),
    ]
