# Generated by Django 5.2 on 2026-04-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='sendcloud_inputs',
            field=models.JSONField(default=dict, help_text='Frozen parcel-creation payload: address_snapshot, item_lines_snapshot, logical_shipping_option, shipping_method_full_name (Sendcloud method name), total_weight_kg, total_order_value, total_item_quantity, sender_address_id, sendcloud_order_reference (strings/decimals as JSON).'),
        ),
    ]
