# Generated by Django 5.2 on 2026-05-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_sendcloud_webhook_tracking_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='When the parcel was confirmed delivered (set from Sendcloud webhook).', null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='sendcloud_carrier_status_message',
            field=models.CharField(blank=True, default='', help_text="Sendcloud parcel status message (human-readable, e.g. 'In transit').", max_length=512),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='sendcloud_last_webhook_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last applied Sendcloud parcel webhook — used to discard stale events.', null=True),
        ),
    ]
