# Generated by Django 5.2 on 2025-10-12 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="country",
        ),
    ]
