# Generated by Django 5.2 on 2025-09-18 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_address_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
    ]
