# Generated by Django 5.2 on 2025-04-23 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_stuffuser_staffuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='note',
            new_name='notes',
        ),
        migrations.DeleteModel(
            name='StaffUser',
        ),
    ]
