# Generated by Django 5.2 on 2025-10-19 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_paymentinformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentinformation',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='paymentinformation',
            name='card_holder_name',
        ),
        migrations.RemoveField(
            model_name='paymentinformation',
            name='card_type',
        ),
        migrations.RemoveField(
            model_name='paymentinformation',
            name='payment_method',
        ),
    ]
