# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_enhance_email_verification_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationtoken',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True, db_index=True),
        ),
    ]

