# Generated by Django 5.2 on 2025-12-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_add_email_sent_at_to_emailverificationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
