# Generated by Django 5.2 on 2025-12-09 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(blank=True, default='GB', help_text='ISO 3166-1 alpha-2 country code (e.g., GB, US)', max_length=2, null=True),
        ),
    ]
