# Generated by Django 5.2 on 2025-12-09 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_address_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
    ]
