# Generated by Django 5.2 on 2026-06-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_customuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created_source',
            field=models.CharField(choices=[('website', 'Website'), ('admin', 'Admin'), ('system', 'System'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20),
        ),
    ]
