# Generated by Django 5.2 on 2026-06-04 16:01

from django.db import migrations, models


def _split_legacy_name(full_name: str):
    full_name = (full_name or "").strip()
    if not full_name:
        return None, None
    parts = full_name.split()
    if len(parts) == 2:
        return parts[0], parts[1]
    return full_name, None


def populate_first_name_surname(apps, schema_editor):
    CustomUser = apps.get_model("account", "CustomUser")
    for user in CustomUser.objects.iterator():
        if user.first_name or user.surname:
            continue
        legacy = (user.name or "").strip()
        if not legacy:
            continue
        first_name, surname = _split_legacy_name(legacy)
        user.first_name = first_name
        user.surname = surname
        display_parts = [p for p in (first_name, surname) if p]
        user.name = " ".join(display_parts) if display_parts else legacy
        user.save(update_fields=["first_name", "surname", "name"])


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_customuser_created_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='surname',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.RunPython(populate_first_name_surname, migrations.RunPython.noop),
    ]
