name: 'Docker Build and Push'
description: 'Build and push Docker images with caching and multi-platform support'

inputs:
  service-name:
    description: 'Service name (backend, frontend-marketplace, nginx, postgres)'
    required: true
  image-name:
    description: 'Full image name (e.g., dedukr/landar-backend)'
    required: true
  context-path:
    description: 'Build context path'
    required: true
  dockerfile-path:
    description: 'Path to Dockerfile'
    required: false
    default: 'Dockerfile'
  push:
    description: 'Whether to push the image'
    required: false
    default: 'true'
  platforms:
    description: 'Target platforms'
    required: false
    default: 'linux/amd64,linux/arm64'
  build-args:
    description: 'Build arguments (multiline)'
    required: false
    default: ''

outputs:
  image-tag:
    description: 'Full image tag with SHA'
    value: ${{ steps.meta.outputs.tags }}
  image-digest:
    description: 'Image digest'
    value: ${{ steps.build.outputs.digest }}

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.image-name }}
        tags: |
          type=raw,value=latest,enable={{is_default_branch}}
          type=sha,prefix={{branch}}-
          type=ref,event=branch
          type=ref,event=pr

    - name: Build and push
      id: build
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context-path }}
        file: ${{ inputs.context-path }}/${{ inputs.dockerfile-path }}
        push: ${{ inputs.push }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: ${{ inputs.platforms }}
        cache-from: type=gha,scope=${{ inputs.service-name }}
        cache-to: type=gha,mode=max,scope=${{ inputs.service-name }}
        build-args: ${{ inputs.build-args }}
