name: 'Setup Backend Environment'
description: 'Setup Python and Django dependencies for backend testing and building'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.12'
  cache-key:
    description: 'Additional cache key suffix'
    required: false
    default: 'default'

outputs:
  cache-hit:
    description: 'Whether cache was hit'
    value: ${{ steps.pip-cache.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Get pip cache directory
      id: pip-cache-dir
      shell: bash
      run: |
        echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT

    - name: Cache pip dependencies
      id: pip-cache
      uses: actions/cache@v4
      with:
        path: ${{ steps.pip-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ inputs.python-version }}-${{ hashFiles('**/requirements.txt') }}-${{ inputs.cache-key }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ inputs.python-version }}-
          ${{ runner.os }}-pip-

    - name: Upgrade pip
      shell: bash
      run: python -m pip install --upgrade pip

    - name: Install backend dependencies
      shell: bash
      working-directory: ./backend
      run: |
        pip install -r requirements.txt

    - name: Install testing dependencies
      shell: bash
      run: |
        pip install coverage pytest pytest-django black flake8 pylint safety bandit
