# Generated by Django 5.2 on 2026-02-13 15:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0040_remove_productreview_unique_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=255)),
                ('file_hash', models.CharField(help_text='SHA-256 hash of the PDF file for deduplication', max_length=64)),
                ('notes', models.TextField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statement_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Statement Batches',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_date', models.CharField(help_text="Date as it appears in statement (e.g., '01 May')", max_length=50)),
                ('statement_date_parsed', models.DateField(blank=True, help_text='Parsed date (year inferred from batch upload date)', null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount in GBP', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payer_name', models.CharField(help_text='Name of the payer from statement', max_length=255)),
                ('raw_line', models.TextField(help_text='Full original line text from PDF')),
                ('match_status', models.CharField(choices=[('matched', 'Matched'), ('suggested', 'Suggested'), ('unmatched', 'Unmatched'), ('rejected', 'Rejected')], default='unmatched', max_length=20)),
                ('confidence_score', models.IntegerField(default=0, help_text='Confidence score 0-100')),
                ('matching_reason', models.TextField(blank=True, help_text='Explanation of why this match was suggested/confirmed')),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_transactions', to=settings.AUTH_USER_MODEL)),
                ('matched_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='api.order')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='reconciliation.statementbatch')),
            ],
            options={
                'verbose_name_plural': 'Bank Transactions',
                'ordering': ['-statement_date_parsed', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.IntegerField(help_text='Confidence score 0-100')),
                ('matching_reason', models.TextField(help_text='Why this order was suggested')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('suggested_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_matches', to='api.order')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_suggestions', to='reconciliation.banktransaction')),
            ],
            options={
                'verbose_name_plural': 'Reconciliation Matches',
                'ordering': ['-confidence_score', '-created_at'],
                'indexes': [models.Index(fields=['transaction', 'confidence_score'], name='reconciliat_transac_2c0d9c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='statementbatch',
            index=models.Index(fields=['file_hash'], name='reconciliat_file_ha_7ff714_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['match_status'], name='reconciliat_match_s_06b58e_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['amount'], name='reconciliat_amount_a77524_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['statement_date_parsed'], name='reconciliat_stateme_9c5a46_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['payer_name'], name='reconciliat_payer_n_6edb98_idx'),
        ),
    ]
