# Generated by Django 5.2 on 2026-03-27 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0041_product_api_product_name_73c704_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_sendcloud', 'Pending Sendcloud'), ('label_created', 'Label created'), ('failed', 'Failed')], db_index=True, default='pending_sendcloud', max_length=32)),
                ('logical_shipping_option', models.CharField(choices=[('uk_standard_small_parcel', 'UK standard small parcel'), ('uk_tracked_24', 'UK Tracked 24'), ('uk_tracked_48', 'UK Tracked 48')], help_text='Internal option; resolved to a live Sendcloud method ID at ship time.', max_length=64)),
                ('address_snapshot', models.JSONField(default=dict, help_text='Recipient name, address lines, city, postcode, country, phone, email.')),
                ('item_lines_snapshot', models.JSONField(default=list, help_text='Order lines: product id, name, qty, unit weight, line total.')),
                ('total_weight_kg', models.DecimalField(decimal_places=3, help_text='Total parcel weight in kilograms at snapshot time.', max_digits=10)),
                ('total_order_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_order_value_currency', models.CharField(default='GBP', max_length=3)),
                ('total_item_quantity', models.PositiveIntegerField(help_text='Total units (sum of line quantities) for Sendcloud quantity field.')),
                ('sender_address_id', models.PositiveIntegerField(help_text='Sendcloud sender address ID copied at creation for audit.')),
                ('label_pdf', models.FileField(blank=True, help_text='Downloaded A6 (or default) label PDF; print from admin/storage.', null=True, upload_to='shipment_labels/%Y/%m/')),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post_shipment', to='api.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendcloud_parcel_id', models.BigIntegerField()),
                ('tracking_number', models.CharField(blank=True, max_length=255)),
                ('carrier_code', models.CharField(blank=True, max_length=64)),
                ('label_normal_printer_url', models.URLField(blank=True, max_length=600)),
                ('label_links', models.JSONField(blank=True, default=dict, help_text='Raw label object from Sendcloud (e.g. normal_printer, A6 URLs).')),
                ('raw_response', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parcel', to='shipment.shipment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['status', 'created_at'], name='shipment_sh_status_330280_idx'),
        ),
    ]
