# Generated by Django 5.2 on 2026-03-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='packaging_weight_kg',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Tare/packaging added at snapshot; included in carrier billable weight.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='total_order_value',
            field=models.DecimalField(decimal_places=2, help_text='Frozen declared value for carrier/customs (typically goods subtotal).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='total_weight_kg',
            field=models.DecimalField(decimal_places=3, help_text='Sum of line weights (goods only) at snapshot time, kilograms.', max_digits=10),
        ),
    ]
