# Generated by Django 5.2 on 2026-03-28 10:54

from django.db import migrations, models


def forwards_shipment_status(apps, schema_editor):
    Shipment = apps.get_model("shipment", "Shipment")
    Shipment.objects.filter(status="pending_sendcloud").update(status="pending")
    Shipment.objects.filter(status="failed").update(status="failed_final")


def backwards_shipment_status_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_ready_to_ship_and_packaging'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='retry_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of failed Sendcloud attempts (incremented before each Celery retry).'),
        ),
        migrations.RunPython(forwards_shipment_status, backwards_shipment_status_noop),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('creating', 'Creating'), ('label_created', 'Label created'), ('failed_retryable', 'Failed (retryable)'), ('failed_final', 'Failed (final)'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=32),
        ),
    ]
