# Generated by Django 5.2 on 2026-03-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0003_shipment_fsm_status_and_retry'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='sendcloud_order_reference',
            field=models.CharField(blank=True, default='', help_text='Stable reference sent as Sendcloud parcel order_number (frozen at snapshot).', max_length=128),
        ),
    ]
