# Generated by Django 5.2 on 2026-03-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0004_sendcloud_order_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentparcel',
            name='label_download_error',
            field=models.TextField(blank=True, default='', help_text='Last error fetching/storing label PDF (parcel may still exist remotely).'),
        ),
        migrations.AddField(
            model_name='shipmentparcel',
            name='label_pdf',
            field=models.FileField(blank=True, help_text='Local copy of the label PDF; distinct from provider_* metadata.', null=True, upload_to='shipment_labels/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='shipmentparcel',
            name='label_stored_at',
            field=models.DateTimeField(blank=True, help_text='When label_pdf was last written successfully.', null=True),
        ),
        migrations.AddField(
            model_name='shipmentparcel',
            name='provider_document_url',
            field=models.URLField(blank=True, default='', help_text='Additional provider document URL (customs, CN23, invoice, etc.).', max_length=600),
        ),
        migrations.AddField(
            model_name='shipmentparcel',
            name='provider_label_url',
            field=models.URLField(blank=True, default='', help_text='Provider shipping-label URL (documents/label or label_printer).', max_length=600),
        ),
        migrations.AddField(
            model_name='shipmentparcel',
            name='provider_status_id',
            field=models.CharField(blank=True, default='', help_text='Sendcloud parcel status.id from provider.', max_length=32),
        ),
        migrations.AddField(
            model_name='shipmentparcel',
            name='provider_status_message',
            field=models.CharField(blank=True, default='', help_text='Sendcloud parcel status.message.', max_length=512),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='label_pdf',
            field=models.FileField(blank=True, help_text='Legacy: label PDF on shipment. Prefer post_shipment.parcel.label_pdf.', null=True, upload_to='shipment_labels/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='shipmentparcel',
            name='label_normal_printer_url',
            field=models.URLField(blank=True, help_text='Deprecated mirror of label URL for older readers; prefer provider_label_url.', max_length=600),
        ),
    ]
