# Generated by Django 5.2 on 2026-03-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0005_parcel_provider_state_and_label_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipmentparcel',
            name='label_download_error',
        ),
        migrations.RemoveField(
            model_name='shipmentparcel',
            name='label_pdf',
        ),
        migrations.RemoveField(
            model_name='shipmentparcel',
            name='label_stored_at',
        ),
        migrations.AddField(
            model_name='shipment',
            name='label_download_status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='not_started', help_text='Local label file pipeline — independent of Sendcloud parcel creation.', max_length=16),
        ),
        migrations.AddField(
            model_name='shipment',
            name='label_downloaded_at',
            field=models.DateTimeField(blank=True, help_text='When the label PDF was stored locally on label_file.', null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='label_file',
            field=models.FileField(blank=True, help_text='Locally stored shipping label PDF (distinct from provider URLs).', null=True, upload_to='shipment_labels/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='provider_created_at',
            field=models.DateTimeField(blank=True, help_text='When Sendcloud accepted the parcel (ShipmentParcel persisted).', null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='label_pdf',
            field=models.FileField(blank=True, help_text='Legacy label PDF; prefer label_file.', null=True, upload_to='shipment_labels/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('creating', 'Creating'), ('provider_created', 'Provider parcel created'), ('label_ready', 'Label file ready'), ('label_created', 'Label created (legacy)'), ('failed_retryable', 'Failed (retryable)'), ('failed_final', 'Failed (final)'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=32),
        ),
    ]
