# Generated by Django 5.2 on 2026-03-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0006_shipment_label_state_split'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='last_error',
            field=models.TextField(blank=True, help_text='Last Sendcloud API or label pipeline error (cleared on success).'),
        ),
    ]
