# Generated by Django 5.2 on 2026-03-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0007_shipment_last_error_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='label_file',
            field=models.FileField(blank=True, help_text='Stored shipping label PDF (S3/media path landars/shipment_labels/; distinct from provider URLs).', null=True, upload_to='landars/shipment_labels/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='label_pdf',
            field=models.FileField(blank=True, help_text='Legacy label PDF; prefer label_file.', null=True, upload_to='landars/shipment_labels/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='total_item_quantity',
            field=models.PositiveIntegerField(help_text='Sum of line item units at snapshot time (manifest); not Sendcloud parcel multi-collo count.'),
        ),
    ]
