# Generated by Django 5.2 on 2026-03-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0008_shipment_label_s3_landars_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='label_pdf',
        ),
        migrations.RemoveField(
            model_name='shipmentparcel',
            name='label_links',
        ),
        migrations.RemoveField(
            model_name='shipmentparcel',
            name='label_normal_printer_url',
        ),
        migrations.RemoveField(
            model_name='shipmentparcel',
            name='provider_document_url',
        ),
        migrations.RemoveField(
            model_name='shipmentparcel',
            name='provider_status_id',
        ),
        migrations.RemoveField(
            model_name='shipmentparcel',
            name='provider_status_message',
        ),
        migrations.RemoveField(
            model_name='shipmentparcel',
            name='raw_response',
        ),
        migrations.AddField(
            model_name='shipmentparcel',
            name='tracking_url',
            field=models.URLField(blank=True, default='', help_text='Carrier tracking page URL from Sendcloud when provided.', max_length=600),
        ),
        migrations.AlterField(
            model_name='shipmentparcel',
            name='provider_label_url',
            field=models.URLField(blank=True, default='', help_text='Provider shipping-label URL (for re-download; authenticated).', max_length=600),
        ),
    ]
