# Generated by Django 5.2 on 2026-03-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0009_slim_parcel_remove_legacy_label_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='label_file',
        ),
        migrations.AddField(
            model_name='shipment',
            name='label_s3_key',
            field=models.CharField(blank=True, default='', help_text='S3 object key for the label PDF (bucket AWS_STORAGE_BUCKET_NAME, region AWS_S3_REGION_NAME); same boto3 helpers as invoices.', max_length=512),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='label_downloaded_at',
            field=models.DateTimeField(blank=True, help_text='When the label PDF was stored in S3 (see label_s3_key).', null=True),
        ),
    ]
