# Generated by Django 5.2 on 2026-03-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0010_label_s3_key_like_invoices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='packaging_weight_kg',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Kept for schema compatibility; always 0 — billable weight uses goods only.', max_digits=10),
        ),
    ]
